[#22]: add enable_token; not required, done for consistency's sake

diff --git a/code/bin/dd-vt-upload-auth-methods b/code/bin/dd-vt-upload-auth-methods
--- a/code/bin/dd-vt-upload-auth-methods
+++ b/code/bin/dd-vt-upload-auth-methods
@@ -241,7 +241,66 @@ function set_up_approle
 }
 
 
-# NOTE: no need to enable token auth method, enabled by default
+# NOTE: token auth method is enabled by default; this is for consistency
+
+function enable_token
+{
+    if [ $# -ne 3 ]
+    then
+        echo "Usage: ${FUNCNAME[0]} <vault host> <token> <conf>"
+        return 1
+    fi
+
+    # TODO: see also enable_approle
+    # TODO: remove duplicate, really similar code here ./. enable_approle
+
+    # vault server protocol, host and port
+    vault_host="${1}"
+
+    # token used to auth; typically the root token
+    token="${2}"
+
+    # auth method conf
+    conf="${3}"
+
+    description="$(jq -r '.description' <<< "${conf}")"
+    root_enable="$(jq -r '.root_enable' <<< "${conf}")"
+    type="$(       jq -r '.type'        <<< "${conf}")"
+
+    req_data="$(jo description="${description}" type="${type}")"
+    full_url="${vault_host}/${root_enable}"
+
+    jq_err='if .errors and (.errors | length) > 0 then .errors[] else empty end'
+
+    echo -n '    enable auth method: '
+    if output="$(curl "${curl_args[@]}"                     \
+                      --data    "${req_data}"               \
+                      --header  "X-Vault-Token: ${token}"   \
+                      --request POST                        \
+                      "${full_url}" 2>&1)"
+    then
+        err_resp="$(jq -r "${jq_err}" <<< "${output}")"
+
+        if [ -z "${err_resp}" ]
+        then
+            echo 'OK'
+        else
+            if [ "${err_resp}" = "path is already in use at token/" ]
+            then
+                echo 'IGNORE ERROR'
+                echo "      ${err_resp}"
+            else
+                echo 'ERROR'
+                echo "          ${err_resp}"
+                return 1
+            fi
+        fi
+    else
+        echo 'ERROR'
+        echo "    ${output}"
+        return 1
+    fi
+}
 
 
 function set_up_token
@@ -675,7 +734,9 @@ do
                                  "${method_conf}"; then exit 1; fi
             ;;
         token)
-            # NOTE: no need to enable token auth method, enabled by default
+            if ! enable_token    "${vault_host}" \
+                                 "${root_token}" \
+                                 "${method_conf}"; then exit 1; fi
             if ! set_up_token    "${vault_host}" \
                                  "${root_token}" \
                                  "${method_conf}"; then exit 1; fi
