[#8]: refactor script to upload secrets to new approach

diff --git a/code/bin/dd-vt-upload-secrets b/code/bin/dd-vt-upload-secrets
--- a/code/bin/dd-vt-upload-secrets
+++ b/code/bin/dd-vt-upload-secrets
@@ -92,8 +92,7 @@ else
 fi
 
 echo -n 'Extract script configuration attributes: '
-for attr in key_file_name path_to_sec_loc placeholder \
-            secrets secrets_folder vault_address
+for attr in key_file_name path_to_sec_loc secrets secrets_folder vault_address
 do
     # https://unix.stackexchange.com/a/68349
     declare "${attr}"="$(jq -r ".${attr}" <<< "${config}")"
@@ -106,15 +105,6 @@ do
     fi
 done
 echo 'OK'
-
-
-# TODO: review jq exprs to make these scalable beyond one path
-
-# json data structure with secrets for each service
-serv_secrets="$(jq '.[] | select(.context=="service")' <<< "${secrets}")"
-
-# json data structure with secrets for each user
-user_secrets="$(jq '.[] | select(.context=="user")'    <<< "${secrets}")"
 
 
 # -----------------------------------------------------------------------------
@@ -130,10 +120,6 @@ if ! validate_secure_location;      then exit 1; fi
 # full path to file with key and token info
 # shellcheck disable=SC2154
 path_to_key_file="${path_to_sec_loc}/${key_file_name}"
-
-# (extended) regex to match integer or float strings
-# TODO: take locale into account ? (SRSLY ?!?)
-re_number='^[0-9]+(.?[0-9])+$'
 
 
 # -----------------------------------------------------------------------------
@@ -159,9 +145,16 @@ fi
 # -----------------------------------------------------------------------------
 # upload secrets
 
-# https://www.vaultproject.io/api/secret/kv/index.html
-
-# TODO: only do this if any services or users are configured
+if [ "${secrets}" = 'null' ]
+then
+    echo 'no secrets configured; skip setup'
+    echo
+    echo 'HashiCorp Vault secrets upload complete'
+    echo
+    exit
+else
+    secret_paths="$(jq -r '.[].path' <<< "${secrets}")"
+fi
 
 root_token="$(jq -r '.root_token' "${path_to_key_file}")"
 
@@ -175,237 +168,116 @@ else
     exit 1
 fi
 
-# TODO: remove code duplication
+# TODO: get this from elsewhere
+jq_err='if .errors and (.errors | length) > 0 then .errors[] else empty end'
 
-if [ -z "${serv_secrets}" ]
+# NOTE: the vault CLI doesn't seem to support listing secrets
+# https://www.vaultproject.io/api/secret/cubbyhole/index.html#list-secrets
+# TODO: support other endpoints than cubbyhole
+full_url="${vault_address}/v1/cubbyhole/"
+
+echo -n 'get existing secrets: '
+if output="$(curl --header  "X-Vault-Token: ${root_token}"      \
+                  --request LIST                                \
+                  --show-error                                  \
+                  --silent                                      \
+                  "${full_url}" 2>&1)"
 then
-    echo 'no services configured; skip uploading service policy files'
-else
-    serv_names="$(jq -r '.sec_confs[].path' <<< "${serv_secrets}" | xargs)"
-fi
-
-for serv_name in ${serv_names}
-do
-    echo "service ${serv_name}:"
-
-    # TODO: do not hard-code file suffix
-    # TODO: really mix service and user secret files in the same folder ?
-    path_to_conf_file="${path_to_sec_loc}/${secrets_folder}/${serv_name}.yaml"
-
-    if [ ! -e "${path_to_conf_file}" ]
-    then
-        echo '  secrets configuration file does not exist; not uploaded:'
-        echo "  ${path_to_conf_file}"
-        continue
-    fi
-
-    # load entire service secrets conf file
-    # NOTE: yq does return json, but in jq "entries" format
-    jq_expr='.[] | from_entries | .secrets = (.secrets | from_entries)'
-
-    echo -n '  get service secrets configuration: '
-    if output="$(yq -j r "${path_to_conf_file}" 2>&1 | jq "${jq_expr}" 2>&1)"
+    if [ -z "$(jq -r "${jq_err}" <<< "${output}")" ]
     then
         echo 'OK'
-        secrets_conf="${output}"
+        exist_secrets_json="${output}"
     else
         echo 'ERROR'
-        echo "  ${output}"
-        continue
+        echo "${output}"
+        exit 1
     fi
-
-    paths="$(jq -r '.path' <<< "${secrets_conf}")"
-
-    for path in ${paths}
-    do
-        # TODO: is it safe to show paths in output ?
-        echo "  path ${path}: "
-
-        echo '    verify secrets configuration: '
-
-        jq_expr="select(.path == \"${path}\").secrets"
-        secrets="$(jq -r "${jq_expr}" <<< "${secrets_conf}")"
-
-        unset_secrets=false
-        OLD_IFS="${IFS}" && IFS=$'\n'
-
-        # verify all secrets were changed after file was generated
-        # https://ilya-sher.org/2016/05/11/most-jq-you-will-ever-need
-        #  --> search for 'Do something with each object'
-        # NOTE: while loop as on page above, unset_secrets is not set
-        json_lines="$(jq -c 'to_entries[]' <<< "${secrets}")"
-        for json_line in ${json_lines}
-        do
-            key="$(  jq -r '.key'   <<< "${json_line}")"
-            value="$(jq -r '.value' <<< "${json_line}")"
-
-            echo -n "      ${path}/${key}: "
-            if [ "${value}" != "${placeholder}" ] && \
-               [ "${value}" != 'null' ] &&  [ -n "${value}" ]
-            then
-                echo 'OK'
-            else
-                echo 'FAIL'
-                echo "      secret has not been set; not uploaded"
-                unset_secrets=true
-                break
-            fi
-
-            # need to re-quote integer or float secret values:
-            # https://github.com/hashicorp/vault/issues/4912
-            if "${grep}" -E -q "${re_number}" <<< "${value}"
-            then
-                secrets="$(jq ".${key} = \"${value}\"" <<< "${secrets}")"
-            fi
-        done
-
-        IFS="${OLD_IFS}"
-
-        if [ "${unset_secrets}" = true ]
-        then
-            continue
-        fi
-
-        echo -n '  upload secrets: '
-
-        full_url="${vault_address}/v1/${path}"
-
-        if output="$(curl --data   "${secrets}"                   \
-                          --header "X-Vault-Token: ${root_token}" \
-                          --request POST                          \
-                          --show-error                            \
-                          --silent                                \
-                          "${full_url}" 2>&1)"
-        then
-            # if successful, curl returns 0 and output is empty
-            if [ -z "${output}" ]
-            then
-                echo 'OK'
-                echo "secrets uploaded to ${full_url}"
-            else
-                echo 'ERROR'
-                # sample output:
-                # {"errors":["1 error occurred:\n\n* permission denied"]}
-                if errors="$(jq -r '.errors[]' <<< "${output}" 2>&1)"
-                then
-                    echo "${errors}"
-                else
-                    echo "${output}"
-                fi
-                exit 1
-            fi
-        else
-            echo 'ERROR'
-            echo "  ${output}"
-            exit 1
-        fi
-    done
-done
-
-
-if [ -z "${user_secrets}" ]
-then
-    echo 'no users configured; skip uploading user secrets files'
 else
-    user_names="$(jq -r '.sec_confs[].path' <<< "${user_secrets}" | xargs)"
+    echo 'ERROR'
+    echo "${output}"
+    exit 1
 fi
 
-for user_name in ${user_names}
+# sample response with no existing secrets:
+# {
+#   "errors": []
+# }
+#
+# sample response with one existing secret:
+# {
+#   "request_id": "fc613730-feb9-f2e7-eb29-8c5db9accd67",
+#   "lease_id": "",
+#   "renewable": false,
+#   "lease_duration": 0,
+#   "data": {
+#     "keys": [
+#       "gitlab_registry_credentials"
+#     ]
+#   },
+#   "wrap_info": null,
+#   "warnings": null,
+#   "auth": null
+# }
+
+jq_expr='if .data.keys then .data.keys[] else empty end'
+exist_secrets="$(jq -r "${jq_expr}" <<< "${exist_secrets_json}")"
+
+# TODO: what to do with existing secrets ? use PUT instead of POST ?
+
+echo 'process secrets configurations:'
+
+for secret_path in ${secret_paths}
 do
-    echo "user ${user_name}:"
+    echo "  ${secret_path}:"
 
-    # TODO: do not hard-code file suffix
-    path_to_conf_file="${path_to_sec_loc}/${secrets_folder}/${user_name}.yaml"
+    jq_expr=".[] | select(.path == \"${secret_path}\")"
+    secret_conf="$(jq "${jq_expr}" <<< "${secrets}")"
 
-    if [ ! -e "${path_to_conf_file}" ]
+    # NOTE: need to use alternate notation due to leading $
+    file_ref="$(jq -r '.["$ref"]' <<< "${secret_conf}")"
+    path_to_secrets_file="${path_to_sec_loc}/${secrets_folder}/${file_ref}"
+
+    if [ ! -e "${path_to_secrets_file}" ]
     then
-        echo '  secrets configuration file does not exist; not uploaded:'
-        echo "  ${path_to_conf_file}"
+        echo '    secrets file does not exist; not uploaded:'
+        echo "    ${path_to_secrets_file}"
         continue
     fi
 
-    # load entire user secrets conf file
-    # NOTE: yq does return json, but in jq "entries" format
-    jq_expr='.[] | from_entries | .secrets = (.secrets | from_entries)'
-
-    echo -n '  get user secrets configuration: '
-    if output="$(yq -j r "${path_to_conf_file}" 2>&1 | jq "${jq_expr}" 2>&1)"
+    echo -n '    load secrets file: '
+    if output="$(yq read "${path_to_secrets_file}" --tojson 2>&1)"
     then
         echo 'OK'
-        secrets_conf="${output}"
+        secrets_json="${output}"
     else
         echo 'ERROR'
-        echo "  ${output}"
-        continue
+        echo "      ${output}"
+        exit 1
     fi
 
-    paths="$(jq -r '.path' <<< "${secrets_conf}")"
+    echo -n '    upload secrets: '
 
-    for path in ${paths}
-    do
-        # TODO: is it safe to show paths in output ?
-        echo -n "  path ${path}: "
-
-        jq_expr="select(.path == \"${path}\").secrets"
-        secrets="$(jq -r "${jq_expr}" <<< "${secrets_conf}")"
-
-        unset_secrets=false
-        OLD_IFS="${IFS}" && IFS=$'\n'
-
-        # verify all secrets were changed after file was generated
-        # https://ilya-sher.org/2016/05/11/most-jq-you-will-ever-need
-        #  --> search for 'Do something with each object'
-        # NOTE: while loop as on page above, unset_secrets is not set
-        json_lines="$(jq -c 'to_entries[]' <<< "${secrets}")"
-        for json_line in ${json_lines}
-        do
-            key="$(  jq -r '.key'   <<< "${json_line}")"
-            value="$(jq -r '.value' <<< "${json_line}")"
-            if [ "${value}" = "${placeholder}" ]
-            then
-                echo 'ERROR'
-                echo "  secret ${path}/${key} has not been set; not uploaded"
-                unset_secrets=true
-                break
-            fi
-        done
-
-        IFS="${OLD_IFS}"
-
-        if [ "${unset_secrets}" = true ]
+    full_url="${vault_address}/v1/${secret_path}"
+    if output="$(curl --data    "${secrets_json}"               \
+                      --header  "X-Vault-Token: ${root_token}"  \
+                      --request POST                            \
+                      --show-error                              \
+                      --silent                                  \
+                      "${full_url}" 2>&1)"
+    then
+        if [ -z "$(jq -r "${jq_err}" <<< "${output}")" ]
         then
-            continue
-        fi
-
-        if output="$(curl --data   "${secrets}"                   \
-                          --header "X-Vault-Token: ${root_token}" \
-                          --request POST                          \
-                          --show-error                            \
-                          --silent                                \
-                          "${vault_address}/v1/${path}" 2>&1)"
-        then
-            # if successful, curl returns 0 and output is empty
-            if [ -z "${output}" ]
-            then
-                echo 'OK'
-            else
-                echo 'ERROR'
-                # sample output:
-                # {"errors":["1 error occurred:\n\n* permission denied"]}
-                if errors="$(jq -r '.errors[]' <<< "${output}" 2>&1)"
-                then
-                    echo "${errors}"
-                else
-                    echo "${output}"
-                fi
-                exit 1
-            fi
+            echo 'OK'
         else
             echo 'ERROR'
-            echo "  ${output}"
-            exit 1
+            echo "${output}"
+            return 1
         fi
-    done
+    else
+        echo 'ERROR'
+        echo "        ${output}"
+        return 1
+    fi
 done
 
 
