[#22]: rewrite script and conf to upload policies; add utility tmpl

diff --git a/code/bin/dd-vt-upload-policies b/code/bin/dd-vt-upload-policies
--- a/code/bin/dd-vt-upload-policies
+++ b/code/bin/dd-vt-upload-policies
@@ -2,7 +2,7 @@
 
 # dd-vt-upload-policies
 #
-# create policies on the vault server
+# upload (i.e. set up) policies to (on) a vault server
 #
 # author  : stefan schablowski
 # contact : stefan.schablowski@desmodyne.com
@@ -33,13 +33,21 @@ path_to_bashlib='/usr/local/lib/dd-bash-lib.sh'
 # absolute path to VaultLib library file
 path_to_vaultlib="${here}/dd-vt-vault.lib"
 
+# name of jinja tmpl file to turn json into hcl, located in
+# path_to_tmpl_root as returned by dd-vt-get-template-path
+name_of_j2h_tmpl='json_2_hcl.j2'
+
 # array with alphabetical list of tools called by this script
 # shellcheck disable=SC2034
-req_tools=('jq' 'vault')
+req_tools=('curl' 'dd-vt-get-template-path' 'jinja2' 'jq' 'vault' 'yq')
 
 # array with paths to append to PATH
 # shellcheck disable=SC2034
 ext_paths=("${here}")
+
+# arguments for every curl call
+# http://stackoverflow.com/a/21109454
+curl_args=('--show-error' '--silent')
 
 
 # -----------------------------------------------------------------------------
@@ -79,8 +87,11 @@ if ! extend_path req_tools ext_paths ; then exit 1; fi
 
 echo
 
+# NOTE: deviating from alphabetical order conv for consistency in
+# dd-vt-upload-auth-methods, dd-vt-upload-policies and dd-vt-upload-secrets
 # shellcheck disable=SC2034
-attrs=(key_file_name path_to_sec_loc policies_folder secrets vault_host)
+attrs=(key_file_name path_to_sec_loc vault_host
+       policies policies_folder policies_root)
 # shellcheck disable=SC2034
 opt_attrs=()
 
@@ -90,19 +101,8 @@ echo 'Load script configuration file:'
 if ! get_attrs_from_yaml_file "${conf_file}" attrs opt_attrs; then exit 1; fi
 
 
-# TODO: review jq exprs to make these scalable beyond one path
-
-# json data structure with secrets for each service
-# shellcheck disable=SC2154
-serv_secrets="$(jq '.[] | select(.context=="service")' <<< "${secrets}")"
-
-# json data structure with secrets for each user
-user_secrets="$(jq '.[] | select(.context=="user")'    <<< "${secrets}")"
-
-
 # -----------------------------------------------------------------------------
 # validate configuration and folder at secure location
-# TODO: really do these both in every sub script ?
 if ! validate_config_settings;      then exit 1; fi
 if ! validate_secure_location;      then exit 1; fi
 
@@ -113,14 +113,6 @@ if ! validate_secure_location;      then exit 1; fi
 # full path to file with key and token info
 # shellcheck disable=SC2154
 path_to_key_file="${path_to_sec_loc}/${key_file_name}"
-
-# TODO: req'd for defunct curl call
-# policy request data template
-# read -r -d '' policy_req_data_tmpl <<'EOT'
-# {
-#     "policy": "path \\"%s\\""
-# }
-# EOT
 
 
 # -----------------------------------------------------------------------------
@@ -147,12 +139,19 @@ fi
 # -----------------------------------------------------------------------------
 # upload policies
 
-# TODO: only do this if any services or users are configured
+# shellcheck disable=SC2154
+if [ -z "${policies}" ] || [ "${policies}" = 'null' ]
+then
+    echo 'no policies configured'
+    echo
+    echo 'HashiCorp Vault policies upload complete'
+    echo
+    exit
+else
+    mapfile -t policies_paths < <(jq -r '.[].path' <<< "${policies}")
+fi
 
 root_token="$(jq -r '.root_token' "${path_to_key_file}")"
-
-# TODO: this fails, address is ignored
-# if output="$(vault login "${root_token}" -address="${vault_host}" 2>&1)"
 
 echo -n 'log into vault: '
 if output="$(vault login -address="${vault_host}" "${root_token}" 2>&1)"
@@ -164,130 +163,225 @@ else
     exit 1
 fi
 
-
-if [ -z "${serv_secrets}" ]
+echo -n 'get own configuration template root path: '
+if output="$(dd-vt-get-template-path 2>&1)"
 then
-    echo 'no services configured; skip uploading service policy files'
+    echo 'OK'
+    path_to_tmpl_root="${output}"
 else
-    serv_names="$(jq -r '.sec_confs[].path' <<< "${serv_secrets}" | xargs)"
+    echo 'ERROR'
+    echo "${output}"
+    exit 1
 fi
 
-for serv_name in ${serv_names}
+# absolute path to template to turn json into hcl
+path_to_j2h_tmpl="${path_to_tmpl_root}/${name_of_j2h_tmpl}"
+
+jq_err='if .errors and (.errors | length) > 0 then .errors[] else empty end'
+
+echo
+echo 'process policies:'
+echo
+echo "  local policies root folder : ${path_to_sec_loc}/${policies_folder}"
+echo "  vault policies root url    : ${vault_host}/${policies_root}"
+
+for policies_path in "${policies_paths[@]}"
 do
-    echo "service ${serv_name}:"
+    echo
 
-    # shellcheck disable=SC2154
-    path_to_conf_file="${path_to_sec_loc}/${policies_folder}/${serv_name}.hcl"
+    jq_expr=".[] | select(.path == \"${policies_path}\")"
+    policies_conf="$(jq "${jq_expr}" <<< "${policies}")"
 
-    if [ ! -e "${path_to_conf_file}" ]
+    file="$(jq -r '.file' <<< "${policies_conf}")"
+    path_to_policies_file="${path_to_sec_loc}/${policies_folder}/${file}"
+
+    if [ ! -e "${path_to_policies_file}" ]
     then
-        echo '  policy configuration file does not exist; not uploaded:'
-        echo "  ${path_to_conf_file}"
-        continue
-    fi
-
-    echo -n '  upload policy: '
-    if output="$(vault policy write -address="${vault_host}" \
-                       "${serv_name}" "${path_to_conf_file}" 2>&1)"
-    then
-        echo 'OK'
-    else
-        echo 'ERROR'
-        echo "  ${output}"
+        echo '  ERROR: policies file does not exist:'
+        echo "    ${path_to_policies_file}"
         exit 1
     fi
 
-    echo "  file uploaded: ${path_to_conf_file}"
-done
-
-
-if [ -z "${user_secrets}" ]
-then
-    echo 'no users configured; skip uploading user policy files'
-else
-    user_names="$(jq -r '.sec_confs[].path' <<< "${user_secrets}" | xargs)"
-fi
-
-for user_name in ${user_names}
-do
-    echo "user ${user_name}:"
-
-    path_to_conf_file="${path_to_sec_loc}/${policies_folder}/${user_name}.hcl"
-
-    if [ ! -e "${path_to_conf_file}" ]
+    echo -n "  load policies from file at : ${file}: "
+    if output="$(yq read "${path_to_policies_file}" --tojson 2>&1)"
     then
-        echo '  policy configuration file does not exist; not uploaded:'
-        echo "  ${path_to_conf_file}"
-        continue
+        echo 'OK'
+        policies_json="${output}"
+    else
+        echo 'ERROR'
+        echo "    ${output}"
+        exit 1
     fi
 
-    # TODO: req'd for defunct curl call
-    # render request data template
-    # shellcheck disable=SC2059
-    # policy_req_data="$( printf "${policy_req_data_tmpl}"  "${path_to_conf_file}")"
+    # NOTE: official HashiCorp Vault docs are pretty useless when it comes to
+    # defining what Vault exactly expects when uploading a policy; they just
+    # mention 'policy document' and provide examples (using HCL), but do not
+    # actally document what a policy document looks like or may contain:
+    # https://www.hashicorp.com/resources/policies-vault/
+    # https://www.vaultproject.io/api-docs/system/policies#create-update-acl-policy
+    # https://www.vaultproject.io/api/system/policy.html#create-update-policy
+    # https://www.vaultproject.io/docs/concepts/policies#policy-syntax
+    # also, there is a lot of obsolete online resources (2015) that do not
+    # mention the required 'policy' key, but use some 'rules' key (or other):
+    # https://www.vaultproject.io/api/system/policy.html#create-update-policy
+    # https://hvac.readthedocs.io/en/stable/usage/ ...
+    #  ... system_backend/policy.html#manipulate-policies
+    # https://github.com/hashicorp/vault/issues/582#issue-104019680
 
-    # TODO: official documentation is absolutely useless:
-    # https://www.vaultproject.io/api/system/policy.html
-    #
-    # TODO: this fails with
-    #   Failed to parse policy: At 1:77: key 'path "/Volumes/VAULT/ ...
-    #    ... secrets/DesmoDyne/vault.desmodyne.com/policies/ssc.hcl"' ...
-    #    ... expected start of object ('{') or assignment ('=')
-    #
-    # if output="$(curl --data   "${policy_req_data}"           \
-    #                   --header "X-Vault-Token: ${root_token}" \
-    #                   --request POST                          \
-    #                   --show-error                            \
-    #                   --silent                                \
-    #               "${vault_host}/v1/sys/policy/${user_name}" 2>&1)"
-    # then
-    #     # if successful, curl returns 0 and output is empty
-    #     if [ -z "${output}" ]
-    #     then
-    #         echo 'OK'
-    #     else
-    #         echo 'ERROR'
-    #         # sample output:
-    #         # {"errors":["1 error occurred:\n\n* permission denied"]}
-    #         if errors="$(jq -r '.errors[]' <<< "${output}" 2>&1)"
-    #         then
-    #             echo "${errors}"
-    #         else
-    #             echo "${output}"
-    #         fi
-    #         exit 1
-    #     fi
-    # fi
-    #
-    # contents of policy_req_data:
+    # echo
+    # echo 'policies_json:'
+    # jq '.' <<< "${policies_json}"
+    # sample output:
+    # policies_json:
+    # [
+    #   {
+    #     "capabilities": [
+    #       "read"
+    #     ],
+    #     "path": "cubbyhole/Projects/MailFlow/Database/feature/database-admin-credentials"
+    #   },
+    #   {
+    #     "capabilities": [
+    #       "read"
+    #     ],
+    #     "path": "cubbyhole/Projects/MailFlow/Database/feature/database-reader-credentials"
+    #   },
+    #   {
+    #     "capabilities": [
+    #       "read"
+    #     ],
+    #     "path": "cubbyhole/Projects/MailFlow/Database/feature/database-root-credentials"
+    #   },
+    #   {
+    #     "capabilities": [
+    #       "read"
+    #     ],
+    #     "path": "cubbyhole/Projects/MailFlow/Database/feature/database-user-credentials"
+    #   }
+    # ]
+
+    # inject 'policies' root key to give
+    # jinja a top level item to iterate over:
+    # https://stackoverflow.com/q/54087843
+    policies_json="$(jq '{ policies: . }' <<< "${policies_json}")"
+
+    # echo
+    # echo 'policies_json:'
+    # jq '.' <<< "${policies_json}"
+    # sample output:
+    # policies_json:
     # {
-    #     "policy": "path \"/Volumes/VAULT/secrets/DesmoDyne/ ...
-    #                        ... vault.desmodyne.com/policies/ssc.hcl\""
+    #   "policies": [
+    #     {
+    #       "capabilities": [
+    #         "read"
+    #       ],
+    #       "path": "cubbyhole/Projects/MailFlow/Database/feature/database-admin-credentials"
+    #     },
+    #     {
+    #       "capabilities": [
+    #         "read"
+    #       ],
+    #       "path": "cubbyhole/Projects/MailFlow/Database/feature/database-reader-credentials"
+    #     },
+    #     {
+    #       "capabilities": [
+    #         "read"
+    #       ],
+    #       "path": "cubbyhole/Projects/MailFlow/Database/feature/database-root-credentials"
+    #     },
+    #     {
+    #       "capabilities": [
+    #         "read"
+    #       ],
+    #       "path": "cubbyhole/Projects/MailFlow/Database/feature/database-user-credentials"
+    #     }
+    #   ]
+    # }
+
+    # turn json into jcl using jinja template
+    # echo -n '    convert policies json into hcl: '
+    if output="$(jinja2 --format=json --strict "${path_to_j2h_tmpl}" \
+                  <<< "${policies_json}" 2>&1)"
+    then
+        # echo 'OK'
+        policies_hcl="${output}"
+    else
+        echo 'ERROR'
+        echo "      ${output}"
+        exit 1
+    fi
+
+    # echo
+    # echo 'policies_hcl:'
+    # echo "${policies_hcl}"
+    # sample output:
+    # policies_hcl:
+    # path "cubbyhole/Projects/MailFlow/Database/feature/database-admin-credentials"
+    # {
+    #   capabilities = [ "read" ]
     # }
     #
-    # TODO: Vault doesn't really seem to have their minds up on how to do this:
-    # from https://www.vaultproject.io/intro/ ...
-    #       ... getting-started/policies.html#writing-the-policy:
-    #   vault policy write my-policy acl.hcl
-    # from https://www.vaultproject.io/api/ ...
-    #       ... system/policy.html#create-update-policy:
-    #   vault write sys/policy/my-policy policy=@my-policy.hcl
+    # path "cubbyhole/Projects/MailFlow/Database/feature/database-reader-credentials"
+    # {
+    #   capabilities = [ "read" ]
+    # }
+    #
+    # path "cubbyhole/Projects/MailFlow/Database/feature/database-root-credentials"
+    # {
+    #   capabilities = [ "read" ]
+    # }
+    #
+    # path "cubbyhole/Projects/MailFlow/Database/feature/database-user-credentials"
+    # {
+    #   capabilities = [ "read" ]
+    # }
 
-    echo -n '  upload policy: '
-    if output="$(vault policy write -address="${vault_host}" \
-                       "${user_name}" "${path_to_conf_file}" 2>&1)"
+    # turn hcl into one line of json with newlines replaced by \n and
+    # " replaced by \"; also inject 'policy' root key expected by vault;
+    # NOTE: alternative approach:
+    # replace new lines by \n: https://stackoverflow.com/a/43967678
+    # policies_hcl_json="$(sed -e 's|$|\\n|' -e 's|"|\\"|g' \
+    #                        <<< "${policies_hcl}"  | tr -d '\n')"
+    # jq arg from shell variable: https://stackoverflow.com/a/40027637
+    jq_expr='{ policy: $policy_value }'
+    policies_json="$(jq -n --arg policy_value "${policies_hcl}" "${jq_expr}")"
+
+    # echo
+    # echo 'policies_json:'
+    # jq '.' <<< "${policies_json}"
+    # sample output:
+    # policies_json:
+    # {
+    #   "policy": "path \"cubbyhole/ ... (some unreadable long line) ... ]\n}"
+    # }
+
+    # TODO: vault converts policies path into lower case
+    full_url="${vault_host}/${policies_root}/${policies_path}"
+
+    echo -n "  upload policies to path at : ${policies_path}: "
+    if output="$(curl "${curl_args[@]}"                         \
+                      --data    "${policies_json}"              \
+                      --header  "X-Vault-Token: ${root_token}"  \
+                      --request POST                            \
+                      "${full_url}" 2>&1)"
     then
-        echo 'OK'
+        if [ -z "$(jq -r "${jq_err}" <<< "${output}")" ]
+        then
+            echo 'OK'
+        else
+            echo 'ERROR'
+            echo "${output}"
+            exit 1
+        fi
     else
         echo 'ERROR'
-        echo "  ${output}"
+        echo "        ${output}"
         exit 1
     fi
-
-    echo "  file uploaded: ${path_to_conf_file}"
 done
 
 
 echo
-echo 'HashiCorp Vault policy upload complete'
+echo 'HashiCorp Vault policies upload complete'
 echo
