[#22]: improve error handling, doc possible Vault responses

diff --git a/code/bin/dd-vt-upload-secrets b/code/bin/dd-vt-upload-secrets
--- a/code/bin/dd-vt-upload-secrets
+++ b/code/bin/dd-vt-upload-secrets
@@ -152,12 +152,33 @@ root_token="$(jq -r '.root_token' "${path_to_key_file}")"
 
 # jq expression to test vault REST API response for errors;
 # returns the (multi-line) error string or null if no error
+# TODO: print errors properly; sample values:
+#   {"errors":["1 error occurred:\n\t* unsupported path\n\n"]}
+#   {
+#     "errors": [
+#       "no data provided"
+#     ]
+#   }
+#   {
+#     "request_id": "58da4235-5968-d05f-48b1-02de85b0c4b2",
+#     "lease_id": "",
+#     "renewable": false,
+#     "lease_duration": 0,
+#     "data": null,
+#     "wrap_info": null,
+#     "warnings": [
+#       "Invalid path for a versioned K/V secrets engine. See ... "
+#     ],
+#     "auth": null
+#   }
 # TODO: refactor this to elsewhere to use it after every curl call
 # https://stackoverflow.com/a/33059058
 # https://stackoverflow.com/a/36330650
 # https://stackoverflow.com/a/38337572
 # https://github.com/stedolan/jq/issues/354#issuecomment-43102213
-jq_err='if .errors and (.errors | length) > 0 then .errors[] else empty end'
+jq_err='if   .errors   and (.errors   | length) > 0 then .errors[] '`
+      `'elif .warnings and (.warnings | length) > 0 then .warnings[] '`
+      `'else empty end'
 
 echo
 echo 'process secrets:'
@@ -210,25 +231,21 @@ do
                       --request POST                            \
                       "${full_url}" 2>&1)"
     then
-        # TODO: do this for all curl calls
-        # TODO: only for dev, remove
-        if [ -n "${output}" ]
-        then
-            echo
-            echo 'vault response:'
-            jq '.' <<< "${output}"
-            echo
-        fi
+        err_resp="$(jq -r "${jq_err}" <<< "${output}")"
 
-        # TODO: print errors properly; sample value:
-        # {"errors":["1 error occurred:\n\t* unsupported path\n\n"]}
-        if [ -z "$(jq -r "${jq_err}" <<< "${output}")" ]
+        if [ -z "${err_resp}" ]
         then
             echo 'OK'
         else
-            echo 'ERROR'
-            echo "${output}"
-            exit 1
+            if [ "${err_resp}" = "path is already in use at userpass/" ]
+            then
+                echo 'IGNORE ERROR'
+                echo "  ${err_resp}"
+            else
+                echo 'ERROR'
+                echo "  ${err_resp}"
+                exit 1
+            fi
         fi
     else
         echo 'ERROR'
