[#8]: align seal script with conv; run after vault was built

diff --git a/code/bin/dd-vt-seal-vault b/code/bin/dd-vt-seal-vault
--- a/code/bin/dd-vt-seal-vault
+++ b/code/bin/dd-vt-seal-vault
@@ -9,58 +9,115 @@
 # created : 2018-02-19
 
 
+# https://www.vaultproject.io/api/system/seal.html
+
+# NOTE: see also dd-vt-init-vault
+
+
 echo
 echo 'Seal HashiCorp Vault'
 echo
-
-
-# https://www.vaultproject.io/api/system/seal.html
-
-
-# -----------------------------------------------------------------------------
-# load functions from library and run as appropriate
-
-# see also build-vault
-
-source dd-vt-vault.lib
-
-if ! determine_platform;            then exit 1; fi
-if ! proc_cmd_line_args "$@";       then exit 1; fi
-
-
-# -----------------------------------------------------------------------------
-# load script configuration
-
-# NOTE: see config file for parameter documentation
-# TODO: error handling, e.g. check if key_file is available
-# TODO: review output, message only if error or -v / --verbose
-
-# http://mikefarah.github.io/yq
-config="$(yq -j r "${config_file}")"
-
-vault_address="$(  jq -r '.vault_address'   <<< "${config}")"
-path_to_sec_loc="$(jq -r '.path_to_sec_loc' <<< "${config}")"
-key_file_name="$(  jq -r '.key_file_name'   <<< "${config}")"
-
-
-# -----------------------------------------------------------------------------
-if ! validate_config_settings;      then exit 1; fi
 
 
 # -----------------------------------------------------------------------------
 # configure script parameters
 
 # absolute path to this script: http://stackoverflow.com/a/9107028
-path_to_this_script="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
+here="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
 
-# path from this script to project root
-rel_path_to_project_root='../..'
+# absolute path to BashLib library file
+path_to_bashlib='/usr/local/lib/dd-bash-lib.sh'
 
-# absolute path to project root
-path_to_project_root="$(realpath \
-                        "${path_to_this_script}/${rel_path_to_project_root}")"
+# absolute path to VaultLib library file
+path_to_vaultlib="${here}/dd-vt-vault.lib"
+
+# array with alphabetical list of tools called by this script
+# shellcheck disable=SC2034
+req_tools=('curl' 'jq' 'yq')
+
+# array with paths to append to PATH
+# shellcheck disable=SC2034
+ext_paths=("${here}")
+
+
+# -----------------------------------------------------------------------------
+# load BashLib and VaultLib
+
+# shellcheck disable=SC1090
+if output="$(source "${path_to_bashlib}" 2>&1)"
+then
+    # shellcheck disable=SC1090
+    source "${path_to_bashlib}"
+else
+    echo "${output}"
+    exit 1
+fi
+
+# shellcheck disable=SC1090
+if output="$(source "${path_to_vaultlib}" 2>&1)"
+then
+    # shellcheck disable=SC1090
+    source "${path_to_vaultlib}"
+else
+    echo "${output}"
+    exit 1
+fi
+
+
+# -----------------------------------------------------------------------------
+# run BashLib boilerplate functions
+
+if ! configure_platform              ; then exit 1; fi
+if ! get_conf_file_arg "${@}"        ; then exit 1; fi
+if ! extend_path req_tools ext_paths ; then exit 1; fi
+
+
+# -----------------------------------------------------------------------------
+# load script configuration
+
+echo
+
+echo -n 'Load script configuration file: '
+# conf_file is defined by get_conf_file_arg
+# shellcheck disable=SC2154
+if output="$(yq read "${conf_file}" --tojson 2>&1)"
+then
+    echo 'OK'
+    config="${output}"
+else
+    echo 'ERROR'
+    echo "${output}"
+    exit 1
+fi
+
+echo -n 'Extract script configuration attributes: '
+for attr in key_file_name path_to_sec_loc vault_address
+do
+    # https://unix.stackexchange.com/a/68349
+    declare "${attr}"="$(jq -r ".${attr}" <<< "${config}")"
+    # https://unix.stackexchange.com/a/41418
+    if [ -z "${!attr}" ] || [ "${!attr}" = 'null' ]
+    then
+        echo 'ERROR'
+        echo "Failed to get ${attr} attribute from configuration"
+        exit 1
+    fi
+done
+echo 'OK'
+
+
+# -----------------------------------------------------------------------------
+# validate configuration and folder at secure location
+# TODO: really do these both in every sub script ?
+if ! validate_config_settings;      then exit 1; fi
+if ! validate_secure_location;      then exit 1; fi
+
+
+# -----------------------------------------------------------------------------
+# configure script parameters
 
 # full path to file with key and token info
+# shellcheck disable=SC2154
 path_to_key_file="${path_to_sec_loc}/${key_file_name}"
 
 
@@ -87,16 +144,12 @@ fi
 # -----------------------------------------------------------------------------
 # seal vault
 
+echo 'seal vault:'
 
-if ! pushd "${path_to_project_root}" > /dev/null
-then
-    echo "failed to pushd to project root ${path_to_project_root}"
-    exit
-fi
-
-
-# TODO: can this be done with a user token obtained by login ?
 root_token="$(jq -r '.root_token' "${path_to_key_file}")"
+
+# TODO: get this from elsewhere
+jq_err='if .errors and (.errors | length) > 0 then .errors[] else empty end'
 
 echo -n 'seal vault: '
 if output="$(curl --header "X-Vault-Token: ${root_token}" \
@@ -105,33 +158,19 @@ if output="$(curl --header "X-Vault-Token: ${root_token}" \
                   --silent                                \
                   "${vault_address}/v1/sys/seal" 2>&1)"
 then
-    # if successful, curl returns 0 and output is empty
-    if [ -z "${output}" ]
+    if [ -z "$(jq -r "${jq_err}" <<< "${output}")" ]
     then
         echo 'OK'
+        exist_secrets_json="${output}"
     else
         echo 'ERROR'
-        # sample output:
-        # {"errors":["1 error occurred:\n\n* permission denied"]}
-        if errors="$(jq -r '.errors[]' <<< "${output}" 2>&1)"
-        then
-            echo "${errors}"
-        else
-            echo "${output}"
-        fi
+        echo "${output}"
         exit 1
     fi
 else
     echo 'ERROR'
     echo "${output}"
     exit 1
-fi
-
-
-if ! popd > /dev/null
-then
-    echo "failed to popd from project root ${path_to_project_root}"
-    exit
 fi
 
 
