[#22]: add any changes to secrets files to git repo and commit

diff --git a/code/bin/dd-vt-download-secrets b/code/bin/dd-vt-download-secrets
--- a/code/bin/dd-vt-download-secrets
+++ b/code/bin/dd-vt-download-secrets
@@ -234,7 +234,8 @@ if ! extend_path req_tools ext_paths ; then exit 1; fi
 echo
 
 # shellcheck disable=SC2034
-attrs=(endpoints key_file_name path_to_sec_loc secrets_folder vault_address)
+attrs=(commit_msg endpoints key_file_name
+       path_to_sec_loc secrets_folder vault_address)
 # shellcheck disable=SC2034
 opt_attrs=()
 
@@ -317,6 +318,35 @@ do
     fi
 done
 
+# https://stackoverflow.com/a/50117376
+# NOTE: this check must be done before adding files to repo
+# NOTE: path_to_sec_loc is not the git repo root; doesn't matter
+if git -C "${path_to_sec_loc}" diff --exit-code --quiet "${path_to_sec_loc}"
+then
+    echo 'no changes to commit'
+else
+    echo -n "add changes to repository: "
+    if output="$(git -C "${path_to_sec_loc}" add --all 2>&1)"
+    then
+        echo 'OK'
+    else
+        echo 'ERROR'
+        echo "${output}"
+        exit 1
+    fi
 
+    echo -n "commit changes to repository: "
+    if output="$(git -C "${path_to_sec_loc}" commit -m "${commit_msg}" 2>&1)"
+    then
+        echo 'OK'
+    else
+        echo 'ERROR'
+        echo "${output}"
+        exit 1
+    fi
+fi
+
+
+echo
 echo 'HashiCorp Vault secrets download complete'
 echo
