[#22]: commit vault init response / status file only if anything changed

diff --git a/code/bin/dd-vt-init-vault b/code/bin/dd-vt-init-vault
--- a/code/bin/dd-vt-init-vault
+++ b/code/bin/dd-vt-init-vault
@@ -213,19 +213,27 @@ else
     exit 1
 fi
 
-# TODO: add vault UUID and public / private info
-git_msg='initialize vault'
-
-echo -n 'commit init response file: '
-# shellcheck disable=SC2154
-if output="$(git -C "${path_to_sec_loc}" \
-                 commit -m "${git_msg}" "${path_to_key_file}" 2>&1)"
+# stage and commit only if anything changed
+# https://stackoverflow.com/a/8123841
+# https://stackoverflow.com/a/2659808
+if git -C "${path_to_sec_loc}" diff-index --quiet HEAD --
 then
-    echo 'OK'
+    echo 'no change to vault init response file'
 else
-    echo 'ERROR:'
-    echo "${output}"
-    exit 1
+    # TODO: add vault UUID and public / private info
+    git_msg='initialize vault'
+
+    echo -n 'commit init response file: '
+    # shellcheck disable=SC2154
+    if output="$(git -C "${path_to_sec_loc}" \
+                     commit -m "${git_msg}" "${path_to_key_file}" 2>&1)"
+    then
+        echo 'OK'
+    else
+        echo 'ERROR:'
+        echo "${output}"
+        exit 1
+    fi
 fi
 
 
diff --git a/code/bin/dd-vt-unseal-vault b/code/bin/dd-vt-unseal-vault
--- a/code/bin/dd-vt-unseal-vault
+++ b/code/bin/dd-vt-unseal-vault
@@ -243,19 +243,27 @@ else
     exit 1
 fi
 
-# TODO: add vault UUID and public / private info
-git_msg='add vault status file'
-
-echo -n 'commit vault info file: '
-# shellcheck disable=SC2154
-if output="$(git -C "${path_to_sec_loc}" \
-                 commit -m "${git_msg}" "${path_to_info_file}" 2>&1)"
+# stage and commit only if anything changed
+# https://stackoverflow.com/a/8123841
+# https://stackoverflow.com/a/2659808
+if git -C "${path_to_sec_loc}" diff-index --quiet HEAD --
 then
-    echo 'OK'
+    echo 'no change to vault status file'
 else
-    echo 'ERROR:'
-    echo "${output}"
-    exit 1
+    # TODO: add vault UUID and public / private info
+    git_msg='add vault status file'
+
+    echo -n 'commit vault info file: '
+    # shellcheck disable=SC2154
+    if output="$(git -C "${path_to_sec_loc}" \
+                     commit -m "${git_msg}" "${path_to_info_file}" 2>&1)"
+    then
+        echo 'OK'
+    else
+        echo 'ERROR:'
+        echo "${output}"
+        exit 1
+    fi
 fi
 
 
