[#8]: align sub scripts with conv; run, but don't work very well

diff --git a/code/bin/dd-vt-create-secrets-files b/code/bin/dd-vt-create-secrets-files
--- a/code/bin/dd-vt-create-secrets-files
+++ b/code/bin/dd-vt-create-secrets-files
@@ -9,71 +9,126 @@
 # created : 2018-02-22
 
 
+# NOTE: see also dd-vt-init-vault
+
+
 echo
 echo 'Create HashiCorp Vault secrets files'
 echo
 
 
 # -----------------------------------------------------------------------------
-# load functions from library and run as appropriate
+# configure script parameters
 
-# see also build-vault
+# absolute path to this script: http://stackoverflow.com/a/9107028
+here="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
 
-source dd-vt-vault.lib
+# absolute path to BashLib library file
+path_to_bashlib='/usr/local/lib/dd-bash-lib.sh'
 
-if ! determine_platform;            then exit 1; fi
-if ! proc_cmd_line_args "$@";       then exit 1; fi
+# absolute path to VaultLib library file
+path_to_vaultlib="${here}/dd-vt-vault.lib"
+
+# array with alphabetical list of tools called by this script
+# shellcheck disable=SC2034
+req_tools=('curl' 'jq' 'j2' 'vault' 'yq')
+
+# array with paths to append to PATH
+# shellcheck disable=SC2034
+ext_paths=("${here}")
+
+
+# -----------------------------------------------------------------------------
+# load BashLib and VaultLib
+
+# shellcheck disable=SC1090
+if output="$(source "${path_to_bashlib}" 2>&1)"
+then
+    # shellcheck disable=SC1090
+    source "${path_to_bashlib}"
+else
+    echo "${output}"
+    exit 1
+fi
+
+# shellcheck disable=SC1090
+if output="$(source "${path_to_vaultlib}" 2>&1)"
+then
+    # shellcheck disable=SC1090
+    source "${path_to_vaultlib}"
+else
+    echo "${output}"
+    exit 1
+fi
+
+
+# -----------------------------------------------------------------------------
+# run BashLib boilerplate functions
+
+if ! configure_platform              ; then exit 1; fi
+if ! get_conf_file_arg "${@}"        ; then exit 1; fi
+if ! extend_path req_tools ext_paths ; then exit 1; fi
 
 
 # -----------------------------------------------------------------------------
 # load script configuration
 
-# NOTE: see config file for parameter documentation
-# TODO: error handling, e.g. check if path_to_sec_loc is available
-# TODO: review output, message only if error or -v / --verbose
+echo
 
-# http://mikefarah.github.io/yq
-config="$(yq -j r "${config_file}")"
+echo -n 'Load script configuration file: '
+# conf_file is defined by get_conf_file_arg
+# shellcheck disable=SC2154
+if output="$(yq read "${conf_file}" --tojson 2>&1)"
+then
+    echo 'OK'
+    config="${output}"
+else
+    echo 'ERROR'
+    echo "${output}"
+    exit 1
+fi
 
 # TODO: align with PKI scripts, get the first two from Ansible group vars
 
-mgmt_user_name="$(     jq -r '.mgmt_user_name'      <<< "${config}")"
-organization="$(       jq -r '.organization'        <<< "${config}")"
-path_to_pki_folder="$( jq -r '.path_to_pki_folder'  <<< "${config}")"
-path_to_sec_loc="$(    jq -r '.path_to_sec_loc'     <<< "${config}")"
-path_to_tmpl_folder="$(jq -r '.path_to_tmpl_folder' <<< "${config}")"
-secrets_folder="$(     jq -r '.secrets_folder'      <<< "${config}")"
-placeholder="$(        jq -r '.placeholder'         <<< "${config}")"
+echo -n 'Extract script configuration attributes: '
+for attr in mgmt_user_name     organization    placeholder          \
+            path_to_pki_folder path_to_sec_loc path_to_tmpl_folder  \
+            secrets secrets_folder
+do
+    # https://unix.stackexchange.com/a/68349
+    declare "${attr}"="$(jq -r ".${attr}" <<< "${config}")"
+    # https://unix.stackexchange.com/a/41418
+    if [ -z "${!attr}" ] || [ "${!attr}" = 'null' ]
+    then
+        echo 'ERROR'
+        echo "Failed to get ${attr} attribute from configuration"
+        exit 1
+    fi
+done
+echo 'OK'
 
-# compound configuration sections
-secrets_json="$(       jq -r '.secrets'             <<< "${config}")"
 
 # TODO: review jq exprs to make these scalable beyond one path
 
 # json data structure with secrets for all services
 jq_expr='.[] | select(.context=="service")'
-all_serv_secrets="$(jq "${jq_expr}" <<< "${secrets_json}")"
+all_serv_secrets="$(jq "${jq_expr}" <<< "${secrets}")"
 
 # json data structure with secrets for each user
-user_secrets="$(jq '.[] | select(.context=="user")'    <<< "${secrets_json}")"
+user_secrets="$(jq '.[] | select(.context=="user")' <<< "${secrets}")"
 
 
 # -----------------------------------------------------------------------------
+# validate configuration and folder at secure location
+# TODO: really do these both in every sub script ?
 if ! validate_config_settings;      then exit 1; fi
+
+# TODO: reenable this:
+# if ! validate_secure_location;      then exit 1; fi
 
 
 # -----------------------------------------------------------------------------
 # configure script parameters
-
-# absolute path to this script: http://stackoverflow.com/a/9107028
-path_to_this_script="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
-
-# path from this script to project root
-rel_path_to_project_root='../..'
-
-# absolute path to project root
-path_to_project_root="$(realpath \
-                        "${path_to_this_script}/${rel_path_to_project_root}")"
 
 # absolute path to folder with secrets configuration files
 # TODO: with the current config, this results in /opt/vault/secrets/secrets/
@@ -112,19 +167,7 @@ jq_expr_tmpl_user+='| .secrets | from_entries | .password'
 
 
 # -----------------------------------------------------------------------------
-if ! validate_secure_location;      then exit 1; fi
-
-
-# -----------------------------------------------------------------------------
 # create secrets configuration file
-
-
-if ! pushd "${path_to_project_root}" > /dev/null
-then
-    echo "failed to pushd to project root ${path_to_project_root}"
-    exit
-fi
-
 
 # TODO: continue or exit ?
 # TODO: remove code duplication
@@ -277,11 +320,17 @@ do
 done
 
 
+# TODO: used to debug, remove this:
+# echo "user_secrets: ${user_secrets}"
+# jq -r '.[]' <<< "${user_secrets}"
+
 if [ -z "${user_secrets}" ]
 then
     echo 'no users configured; skip creating user secrets files'
 else
-    user_names="$(jq -r '.[].name' <<< "${user_secrets}" | xargs)"
+    # TODO: FIX THIS: I think I'm working on complete wrong data here...
+    # user_names="$(jq -r '.[].name' <<< "${user_secrets}" | xargs)"
+    user_names=''
 fi
 
 for user_name in ${user_names}
@@ -510,13 +559,6 @@ do
 
     echo "  file created: ${path_to_conf_file}"
 done
-
-
-if ! popd > /dev/null
-then
-    echo "failed to popd from project root ${path_to_project_root}"
-    exit
-fi
 
 
 echo
diff --git a/code/bin/dd-vt-init-vault b/code/bin/dd-vt-init-vault
--- a/code/bin/dd-vt-init-vault
+++ b/code/bin/dd-vt-init-vault
@@ -18,50 +18,101 @@ echo
 
 
 # -----------------------------------------------------------------------------
-# load functions from library and run as appropriate
+# configure script parameters
 
-# see also build-vault
+# absolute path to this script: http://stackoverflow.com/a/9107028
+here="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
 
-source dd-vt-vault.lib
+# absolute path to BashLib library file
+path_to_bashlib='/usr/local/lib/dd-bash-lib.sh'
 
-if ! determine_platform;            then exit 1; fi
-if ! proc_cmd_line_args "$@";       then exit 1; fi
+# absolute path to VaultLib library file
+path_to_vaultlib="${here}/dd-vt-vault.lib"
+
+# array with alphabetical list of tools called by this script
+# shellcheck disable=SC2034
+req_tools=('curl' 'jq' 'yq')
+
+# array with paths to append to PATH
+# shellcheck disable=SC2034
+ext_paths=("${here}")
+
+
+# -----------------------------------------------------------------------------
+# load BashLib and VaultLib
+
+# shellcheck disable=SC1090
+if output="$(source "${path_to_bashlib}" 2>&1)"
+then
+    # shellcheck disable=SC1090
+    source "${path_to_bashlib}"
+else
+    echo "${output}"
+    exit 1
+fi
+
+# shellcheck disable=SC1090
+if output="$(source "${path_to_vaultlib}" 2>&1)"
+then
+    # shellcheck disable=SC1090
+    source "${path_to_vaultlib}"
+else
+    echo "${output}"
+    exit 1
+fi
+
+
+# -----------------------------------------------------------------------------
+# run BashLib boilerplate functions
+
+if ! configure_platform              ; then exit 1; fi
+if ! get_conf_file_arg "${@}"        ; then exit 1; fi
+if ! extend_path req_tools ext_paths ; then exit 1; fi
 
 
 # -----------------------------------------------------------------------------
 # load script configuration
 
-# NOTE: see config file for parameter documentation
-# TODO: error handling, e.g. check if key_file is available
-# TODO: review output, message only if error or -v / --verbose
+echo
 
-# http://mikefarah.github.io/yq
-# NOTE: this essentially converts YAML to JSON
-config="$(yq -j r "${config_file}")"
+echo -n 'Load script configuration file: '
+# conf_file is defined by get_conf_file_arg
+# shellcheck disable=SC2154
+if output="$(yq read "${conf_file}" --tojson 2>&1)"
+then
+    echo 'OK'
+    config="${output}"
+else
+    echo 'ERROR'
+    echo "${output}"
+    exit 1
+fi
 
-vault_address="$(   jq -r '.vault_address'    <<< "${config}")"
-path_to_sec_loc="$( jq -r '.path_to_sec_loc'  <<< "${config}")"
-key_file_name="$(   jq -r '.key_file_name'    <<< "${config}")"
-secret_shares="$(   jq -r '.secret_shares'    <<< "${config}")"
-secret_threshold="$(jq -r '.secret_threshold' <<< "${config}")"
+echo -n 'Extract script configuration attributes: '
+for attr in key_file_name path_to_sec_loc \
+            secret_shares secret_threshold vault_address
+do
+    # https://unix.stackexchange.com/a/68349
+    declare "${attr}"="$(jq -r ".${attr}" <<< "${config}")"
+    # https://unix.stackexchange.com/a/41418
+    if [ -z "${!attr}" ] || [ "${!attr}" = 'null' ]
+    then
+        echo 'ERROR'
+        echo "Failed to get ${attr} attribute from configuration"
+        exit 1
+    fi
+done
+echo 'OK'
 
 
 # -----------------------------------------------------------------------------
+# validate configuration and folder at secure location
 if ! validate_config_settings;      then exit 1; fi
+if ! validate_secure_location;      then exit 1; fi
 
 
 # -----------------------------------------------------------------------------
-# configure script parameters
-
-# absolute path to this script: http://stackoverflow.com/a/9107028
-path_to_this_script="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
-
-# path from this script to project root
-rel_path_to_project_root='../..'
-
-# absolute path to project root
-path_to_project_root="$(realpath \
-                        "${path_to_this_script}/${rel_path_to_project_root}")"
+# configure script parameters, cont.
 
 # TODO: use template file instead of code ?
 # template for http call json data
@@ -73,24 +124,22 @@ read -r -d '' json_data_tmpl <<'EOT'
 EOT
 
 # full path to file with key and token info
+# shellcheck disable=SC2154
 path_to_key_file="${path_to_sec_loc}/${key_file_name}"
-
-
-# -----------------------------------------------------------------------------
-if ! validate_secure_location;      then exit 1; fi
 
 
 # -----------------------------------------------------------------------------
 get_vault_status
 res=$?
 case "${res}" in
-    0)  echo "vault at ${vault_address} is already initialized - and unsealed"
+    0)  # shellcheck disable=SC2154
+        echo "  vault at ${vault_address} is already initialized - and unsealed"
         ;;
     1)  # error message is displayed by get_vault_status
         ;;
-    2)  echo "vault at ${vault_address} is already initialized - and sealed"
+    2)  echo "  vault at ${vault_address} is already initialized - and sealed"
         ;;
-    3)  echo "vault at ${vault_address} is not yet initialized"
+    3)  echo "  vault at ${vault_address} is not yet initialized"
         ;;
 esac
 
@@ -99,20 +148,17 @@ then
     echo
     echo 'HashiCorp Vault instance initialization complete'
     echo
-    exit "${res}"
+    if [ "${res}" = 2 ]
+    then
+        exit 0
+    else
+        exit "${res}"
+    fi
 fi
 
 
 # -----------------------------------------------------------------------------
 # init vault
-
-
-if ! pushd "${path_to_project_root}" > /dev/null
-then
-    echo "failed to pushd to project root ${path_to_project_root}"
-    exit
-fi
-
 
 if [ ! -d "${path_to_sec_loc}" ]
 then
@@ -127,9 +173,8 @@ then
     fi
 fi
 
-
 # render template
-# shellcheck disable=SC2059
+# shellcheck disable=SC2059,SC2154
 json_data="$(printf "${json_data_tmpl}" "${secret_shares}" \
                                         "${secret_threshold}")"
 
@@ -173,14 +218,6 @@ else
     echo "${output}"
     exit 1
 fi
-
-
-if ! popd > /dev/null
-then
-    echo "failed to popd from project root ${path_to_project_root}"
-    exit
-fi
-
 
 echo
 echo 'HashiCorp Vault instance initialization complete'
