[#22]: rewrite script and conf to upload secrets

diff --git a/code/bin/dd-vt-upload-secrets b/code/bin/dd-vt-upload-secrets
--- a/code/bin/dd-vt-upload-secrets
+++ b/code/bin/dd-vt-upload-secrets
@@ -2,7 +2,7 @@
 
 # dd-vt-upload-secrets
 #
-# upload all secrets to a vault server
+# upload secrets to a vault server
 #
 # author  : stefan schablowski
 # contact : stefan.schablowski@desmodyne.com
@@ -12,7 +12,7 @@
 # https://www.vaultproject.io/docs/commands/write.html
 # https://www.vaultproject.io/intro/getting-started/first-secret.html
 
-# NOTE: see also dd-vt-init-vault
+# NOTE: see also dd-vt-init-vault and dd-vt-upload-policies
 
 
 echo
@@ -82,11 +82,13 @@ if ! extend_path req_tools ext_paths ; then exit 1; fi
 
 echo
 
+# NOTE: deviating from alphabetical order conv for consistency in
+# dd-vt-upload-auth-methods, dd-vt-upload-policies and dd-vt-upload-secrets
 # shellcheck disable=SC2034
-attrs=(key_file_name path_to_sec_loc secrets_folder vault_host vault_root)
-# NOTE: this must work even if no secrets
+attrs=(key_file_name path_to_sec_loc vault_host
+       secrets secrets_folder secrets_root)
 # shellcheck disable=SC2034
-opt_attrs=(secrets)
+opt_attrs=()
 
 echo 'Load script configuration file:'
 
@@ -107,10 +109,6 @@ if ! validate_secure_location;      then exit 1; fi
 # full path to file with key and token info
 # shellcheck disable=SC2154
 path_to_key_file="${path_to_sec_loc}/${key_file_name}"
-
-# full path to root of folders with secrets config files
-# shellcheck disable=SC2154
-path_to_secrets_root="${path_to_sec_loc}/${secrets_folder}"
 
 
 # -----------------------------------------------------------------------------
@@ -137,7 +135,6 @@ fi
 # -----------------------------------------------------------------------------
 # upload secrets
 
-# TODO: review criterion; e.g. secrets = '', secrets = []
 # shellcheck disable=SC2154
 if [ -z "${secrets}" ] || [ "${secrets}" = 'null' ]
 then
@@ -147,11 +144,17 @@ then
     echo
     exit
 else
-    secret_paths="$(jq -r '.[].path' <<< "${secrets}")"
+    mapfile -t secrets_paths < <(jq -r '.[].path' <<< "${secrets}")
 fi
 
+# TODO: refactor this out to remove code duplication
 root_token="$(jq -r '.root_token' "${path_to_key_file}")"
 
+# https://www.vaultproject.io/docs/commands/login.html
+# TODO: do this using curl to remove dependency on vault client
+# TODO: logging in using the vault client establishes a session
+# which is not required nor used when using curl later on;
+# also, this stores the token locally in ~/.vault-token
 echo -n 'log into vault: '
 if output="$(vault login -address="${vault_host}" "${root_token}" 2>&1)"
 then
@@ -162,33 +165,41 @@ else
     exit 1
 fi
 
-# TODO: get this from elsewhere
-jqe_error='if .errors and (.errors | length) > 0 then .errors[] else empty end'
+# jq expression to test vault REST API response for errors;
+# returns the (multi-line) error string or null if no error
+# TODO: refactor this to elsewhere to use it after every curl call
+# https://stackoverflow.com/a/33059058
+# https://stackoverflow.com/a/36330650
+# https://stackoverflow.com/a/38337572
+# https://github.com/stedolan/jq/issues/354#issuecomment-43102213
+jq_err='if .errors and (.errors | length) > 0 then .errors[] else empty end'
 
 echo
 echo 'process secrets:'
+echo
+echo "  local secrets root folder : ${path_to_sec_loc}/${secrets_folder}"
+echo "  vault secrets root url    : ${vault_host}/${secrets_root}"
 
-for secret_path in ${secret_paths}
+# TODO: clearly distinguish between singular and plural
+# TODO: handle case of no secrets paths
+for secrets_path in "${secrets_paths[@]}"
 do
-    echo "  ${secret_path}:"
+    echo
 
-    jq_expr=".[] | select(.path == \"${secret_path}\")"
-    secret_conf="$(jq "${jq_expr}" <<< "${secrets}")"
+    jq_expr=".[] | select(.path == \"${secrets_path}\")"
+    secrets_conf="$(jq "${jq_expr}" <<< "${secrets}")"
 
-    file="$(jq -r '.file' <<< "${secret_conf}")"
-    path_to_secrets_file="${path_to_secrets_root}/${file}"
+    file="$(jq -r '.file' <<< "${secrets_conf}")"
+    path_to_secrets_file="${path_to_sec_loc}/${secrets_folder}/${file}"
 
     if [ ! -e "${path_to_secrets_file}" ]
     then
-        echo '    secrets file does not exist; not uploaded:'
+        echo '  ERROR: secrets file does not exist:'
         echo "    ${path_to_secrets_file}"
-        continue
+        exit 1
     fi
 
-    # TODO: find a way that does not require using yq,
-    # this line is the only reason for yq as brew dependency
-    echo    '    load secrets from file at'
-    echo -n "    ${path_to_secrets_file}: "
+    echo -n "  load secrets from file at : ${file}: "
     if output="$(yq read "${path_to_secrets_file}" --tojson 2>&1)"
     then
         echo 'OK'
@@ -199,28 +210,29 @@ do
         exit 1
     fi
 
-    full_url="${vault_host}/${vault_root}/${secret_path}"
+    full_url="${vault_host}/${secrets_root}/${secrets_path}"
 
-    echo    '    upload secrets to vault at'
-    echo -n "    ${full_url}: "
+    echo -n "  upload secrets to path at : ${secrets_path}: "
     if output="$(curl "${curl_args[@]}"                         \
                       --data    "${secrets_json}"               \
                       --header  "X-Vault-Token: ${root_token}"  \
                       --request POST                            \
                       "${full_url}" 2>&1)"
     then
-        if [ -z "$(jq -r "${jqe_error}" <<< "${output}")" ]
+        # TODO: print errors properly; sample value:
+        # {"errors":["1 error occurred:\n\t* unsupported path\n\n"]}
+        if [ -z "$(jq -r "${jq_err}" <<< "${output}")" ]
         then
             echo 'OK'
         else
             echo 'ERROR'
             echo "${output}"
-            return 1
+            exit 1
         fi
     else
         echo 'ERROR'
         echo "        ${output}"
-        return 1
+        exit 1
     fi
 done
 
