[#13]: get settings from configration file instead of hardcoding them

diff --git a/code/secrets/extract-secrets b/code/secrets/extract-secrets
--- a/code/secrets/extract-secrets
+++ b/code/secrets/extract-secrets
@@ -29,6 +29,90 @@ esac
 
 
 # -----------------------------------------------------------------------------
+# define functions
+
+# http://stackoverflow.com/a/6212408
+
+function usage
+{
+
+    # TODO: do not use global variables
+    # TODO: space between << and 'EOT' makes a
+    # difference for atom syntax highlighting
+    # TODO: align properly and remove leading space when printing ?
+
+    read -r -d '' msg_tmpl <<'EOT'
+Usage: %s <config file>
+
+mandatory arguments:
+  config file           path to configuration file
+
+optional arguments:
+  -?, --help            print this help message
+EOT
+
+    # shellcheck disable=SC2059
+    printf "${msg_tmpl}\\n" "${script_name}"
+}
+
+
+# -----------------------------------------------------------------------------
+# process command line arguments
+
+# name of this script: http://stackoverflow.com/q/192319
+script_name="$(basename "$0")"
+
+if [ $# -ne 1 ]
+then
+    usage
+    exit 1
+fi
+
+# http://stackoverflow.com/a/14203146
+while [ $# -gt 0 ]
+do
+    key="$1"
+
+    case "${key}" in
+      # NOTE: must escape -?, seems to act as wildcard otherwise
+      -\?|--help) usage; exit 1 ;;
+
+      *)  if [ -z "${config_file}" ]
+          then
+              config_file="$1"
+          else
+              usage
+              exit 1
+          fi
+    esac
+
+    # move past argument or value
+    shift
+done
+
+# TODO: try to use ~/.<script_name>.yaml or so if no config file is passed ?
+
+# config file is a mandatory command line argument
+if [ -z "${config_file}" ]
+then
+    usage
+    exit 1
+fi
+
+if [ ! -e "${config_file}" ]
+then
+    echo "${config_file}: No such file or directory"
+    exit 1
+fi
+
+if [ ! -r "${config_file}" ]
+then
+    echo "${config_file}: File is not readable"
+    exit 1
+fi
+
+
+# -----------------------------------------------------------------------------
 # configure script parameters
 
 # absolute path to this script: http://stackoverflow.com/a/9107028
@@ -41,24 +125,26 @@ rel_path_to_project_root='../..'
 path_to_project_root="$(realpath \
                         "${path_to_this_script}/${rel_path_to_project_root}")"
 
-# path to root folder of location to scan, relative to project root
-# TODO: get this in as cmd line argument
-# TODO: scan entire source project folder
-source_folder='../desmodyne'
-# source_folder='../desmodyne/environments/development'
 
-# path to folder where secrets files are mirrored, relative to project root
-path_to_mirror_folder='data/mirror'
+# -----------------------------------------------------------------------------
+# load script configuration
 
-# regex for strings that indicate secrets
-secrets_regex='API_KEY|PASSWORD|USERNAME'
+# NOTE: see config file for parameter documentation
+# TODO: error handling, e.g. check if json / yaml keys are available
 
-# regex for a <secret path>:<secret name>=<secret value> line
-line_regex='([^ ]+):([0-9]+):[ -]*([A-Z_]+)=([^ ]+)$'
+# http://mikefarah.github.io/yq
+# NOTE: this essentially converts YAML to JSON
+config="$(yq r -j "${config_file}")"
+
+# NOTE: without -r, double quotes around values cause grep to fail with code 2
+source_folder="$(jq -r '.source_folder' <<< "${config}")"
+target_folder="$(jq -r '.target_folder' <<< "${config}")"
+secrets_regex="$(jq -r '.secrets_regex' <<< "${config}")"
+line_regex="$(   jq -r '.line_regex'    <<< "${config}")"
 
 
 # -----------------------------------------------------------------------------
-# build basic Docker images
+# extract secrets from target project
 
 
 if ! pushd "${path_to_project_root}" > /dev/null
@@ -69,11 +155,11 @@ fi
 
 
 echo -n 'scan for lines that possibly contain secrets: '
-# NOTE: macOS / BSD grep returns 2 in some cases, possibly when error messages
-# were suppressed using -s; GNU grep returns 0 - and also is a lot faster...
-# NOTE: if source_folder doesn't exist, BSD grep fails without error message
-# TODO: need to pass -s to ignore broken (?) symlink .../app/web/index.php
-if output="$("${grep}" -EHnrs "${secrets_regex}" "${source_folder}" 2>&1)"
+
+# NOTE: GNU grep seems _massively_ faster that macOS / BSD grep
+# NOTE: if source_folder doesn't exist, grep fails without error message
+# might have to add -s switch to (BSD ?) grep to suppress error message
+if output="$("${grep}" -EHnr "${secrets_regex}" "${source_folder}" 2>&1)"
 then
     echo 'OK'
     grep_output="${output}"
@@ -105,12 +191,12 @@ do
         echo "secret name     : ${secret_name}"
         echo "secret value    : ${secret_value}"
 
-        output_folder="${path_to_mirror_folder}/${path_into_project}"
+        output_folder="${target_folder}/${path_into_project}"
         output_path="${output_folder}/${target_filename}"
         mkdir -p "${output_folder}"
         touch "${output_path}"
 
-        if grep -q "${secret_name}=${secret_value}" "${output_path}"
+        if "${grep}" -q "${secret_name}=${secret_value}" "${output_path}"
         then
             echo 'secret exists'
         else
