[#14]: add first version of script, extracts secrets from target folder

diff --git a/code/secrets/upload-secrets b/code/secrets/upload-secrets
--- a/code/secrets/upload-secrets
+++ b/code/secrets/upload-secrets
@@ -1,16 +1,15 @@
 #!/usr/bin/env bash
 
-# extract-secrets
+# upload-secrets
 #
-# scan directory for secrets and mirror the files that contain them
+# upload secrets to HashiCorp Vault server
 #
 # author  : stefan schablowski
 # contact : stefan.schablowski@desmodyne.com
-# created : 2018-07-06
+# created : 2018-07-07
 
 
-# TODO: must run 'git secret reveal -f' in target repo before adding new secrets
-# TODO: verify there are no duplicate secrets in the same output file ?
+# TODO: must run 'git secret reveal -f' in target repo to access clear text secrets
 
 
 # -----------------------------------------------------------------------------
@@ -19,11 +18,9 @@
 case "${OSTYPE}" in
     darwin*)
         grep='ggrep'
-        sed='gsed'
         ;;
     linux-*)
         grep='grep'
-        sed='sed'
         ;;
     *)
         echo "Unsupported operating system: ${OSTYPE}"
@@ -46,13 +43,12 @@ function usage
     # TODO: align properly and remove leading space when printing ?
 
     read -r -d '' msg_tmpl <<'EOT'
-Usage: %s <config file> <source folder> <target folder>
+Usage: %s <config file> <secrets folder>
 
 mandatory arguments:
   config file           path to configuration file
-  source folder         path to folder to migrate secrets from
-  target folder         path to folder to migrate secrets to
-both source and target folders are typically repository / project root folders
+  secrets folder        path to folder with secrets
+secrets folder is typically a repository / project root folder
 
 optional arguments:
   -?, --help            print this help message
@@ -69,7 +65,7 @@ EOT
 # name of this script: http://stackoverflow.com/q/192319
 script_name="$(basename "$0")"
 
-if [ $# -ne 3 ]
+if [ $# -ne 2 ]
 then
     usage
     exit 1
@@ -87,12 +83,9 @@ do
       *)  if   [ -z "${config_file}" ]
           then
               config_file="$1"
-          elif [ -z "${source_folder}" ]
+          elif [ -z "${secrets_folder}" ]
           then
-              source_folder="$1"
-          elif [ -z "${target_folder}" ]
-          then
-              target_folder="$1"
+              secrets_folder="$1"
           else
               usage
               exit 1
@@ -106,9 +99,7 @@ done
 # TODO: try to use ~/.<script_name>.yaml or so if no config file is passed ?
 
 # verify mandatory command line arguments were passed
-if [ -z "${config_file}"   ] || \
-   [ -z "${source_folder}" ] || \
-   [ -z "${target_folder}" ]
+if [ -z "${config_file}" ] || [ -z "${secrets_folder}" ]
 then
     usage
     exit 1
@@ -126,27 +117,15 @@ then
     exit 1
 fi
 
-if [ ! -e "${source_folder}" ]
+if [ ! -e "${secrets_folder}" ]
 then
-    echo "${source_folder}: No such file or directory"
+    echo "${secrets_folder}: No such file or directory"
     exit 1
 fi
 
-if [ ! -r "${source_folder}" ]
+if [ ! -r "${secrets_folder}" ]
 then
-    echo "${source_folder}: Folder is not readable"
-    exit 1
-fi
-
-if [ ! -e "${target_folder}" ]
-then
-    echo "${target_folder}: No such file or directory"
-    exit 1
-fi
-
-if [ ! -r "${target_folder}" ]
-then
-    echo "${target_folder}: Folder is not readable"
+    echo "${secrets_folder}: Folder is not readable"
     exit 1
 fi
 
@@ -175,13 +154,13 @@ path_to_project_root="$(realpath \
 # NOTE: this essentially converts YAML to JSON
 config="$(yq r -j "${config_file}")"
 
-# NOTE: without -r, double quotes around values cause grep to fail with code 2
-secrets_regex="$(jq -r '.secrets_regex' <<< "${config}")"
-line_regex="$(   jq -r '.line_regex_ex' <<< "${config}")"
+# NOTE: without -r, double quotes around values might cause tools to fail
+secrets_suffix="$(jq -r '.secrets_suffix' <<< "${config}")"
+line_regex="$(    jq -r '.line_regex_up' <<< "${config}")"
 
 
 # -----------------------------------------------------------------------------
-# extract secrets from target project
+# upload secrets to HashiCorp Vault server
 
 
 if ! pushd "${path_to_project_root}" > /dev/null
@@ -191,15 +170,12 @@ then
 fi
 
 
-echo -n 'scan for lines that possibly contain secrets: '
+echo -n 'scan for secrets files: '
 
-# NOTE: GNU grep seems _massively_ faster that macOS / BSD grep
-# NOTE: if source_folder doesn't exist, grep fails without error message
-# might have to add -s switch to (BSD ?) grep to suppress error message
-if output="$("${grep}" -EHnr "${secrets_regex}" "${source_folder}" 2>&1)"
+if output="$(find "${secrets_folder}" -name "*${secrets_suffix}" 2>&1)"
 then
     echo 'OK'
-    grep_output="${output}"
+    find_output="${output}"
 else
     echo 'ERROR'
     echo "${output}"
@@ -210,40 +186,36 @@ echo 'extract location and secret:'
 
 OLD_IFS="${IFS}" && IFS=$'\n'
 
-for line in ${grep_output}
+for filename in ${find_output}
 do
-    if "${grep}" -Eq "${line_regex}" <<< "${line}"
+    # full path to unencrypted secrets file
+    unenc_path="${filename%${secrets_suffix}}"
+
+    if [ ! -e "${unenc_path}" ]
     then
-        source_path="$( "${sed}" -E "s|${line_regex}|\1|g" <<< "${line}")"
-        source_line="$( "${sed}" -E "s|${line_regex}|\2|g" <<< "${line}")"
-        secret_name="$( "${sed}" -E "s|${line_regex}|\3|g" <<< "${line}")"
-        secret_value="$("${sed}" -E "s|${line_regex}|\4|g" <<< "${line}")"
-
-        path_into_project="${source_path#$source_folder}"
-        # TODO: need to remove leading / - do this in one line ?
-        path_into_project="$(dirname  "${path_into_project:1}")"
-        target_filename="$(  basename "${source_path}")"
-
-        echo "secret location : ${source_path}:${source_line}"
-        echo "secret name     : ${secret_name}"
-        echo "secret value    : ${secret_value}"
-
-        output_folder="${target_folder}/${path_into_project}"
-        output_path="${output_folder}/${target_filename}"
-        mkdir -p "${output_folder}"
-        touch "${output_path}"
-
-        if "${grep}" -q "${secret_name}=${secret_value}" "${output_path}"
-        then
-            echo 'secret exists'
-        else
-            echo "${secret_name}=${secret_value}" >> "${output_path}"
-            echo 'secret added'
-        fi
-
-        echo
+        echo "failed to find unencrypted version of ${filename}"
+        echo "you might have to run 'git secret reveal -f' in secrets repo"
+        exit 1
     fi
 
+    lines=$(<"${unenc_path}")
+    for line in ${lines}
+    do
+        if ! "${grep}" -Eq "${line_regex}" <<< "${line}"
+        then
+            echo "line ${line} in ${unenc_path} does not match expected pattern"
+            exit 1
+        fi
+
+        secret_name="$( cut -d '=' -f 1 <<< "${line}")"
+        secret_value="$(cut -d '=' -f 2 <<< "${line}")"
+
+        # TODO: does this line in file matter ?
+        echo "secret location : ${unenc_path}"
+        echo "secret name     : ${secret_name}"
+        echo "secret value    : ${secret_value}"
+        echo
+    done
 done
 
 IFS="${OLD_IFS}"
