[#14]: upload secrets to vault; client token still hardcoded

diff --git a/code/secrets/upload-secrets b/code/secrets/upload-secrets
--- a/code/secrets/upload-secrets
+++ b/code/secrets/upload-secrets
@@ -10,6 +10,7 @@
 
 
 # TODO: must run 'git secret reveal -f' in target repo to access clear text secrets
+# TODO: merge / align this with .../code/vault/upload-secrets ?
 
 
 # -----------------------------------------------------------------------------
@@ -143,6 +144,9 @@ rel_path_to_project_root='../..'
 path_to_project_root="$(realpath \
                         "${path_to_this_script}/${rel_path_to_project_root}")"
 
+# vault path prefix for all secrets, somewhat unchangeably set by vault
+vault_prefix='v1/secret'
+
 
 # -----------------------------------------------------------------------------
 # load script configuration
@@ -155,6 +159,7 @@ path_to_project_root="$(realpath \
 config="$(yq r -j "${config_file}")"
 
 # NOTE: without -r, double quotes around values might cause tools to fail
+vault_address="$( jq -r '.vault_address'  <<< "${config}")"
 secrets_suffix="$(jq -r '.secrets_suffix' <<< "${config}")"
 line_regex="$(    jq -r '.line_regex'     <<< "${config}")"
 
@@ -182,12 +187,15 @@ else
     exit 1
 fi
 
-echo 'extract location and secret:'
+echo "upload secrets from secrets folder ${secrets_folder} to vault at ${vault_address}:"
+echo
 
 OLD_IFS="${IFS}" && IFS=$'\n'
 
 for filename in ${find_output}
 do
+    echo "${filename}:"
+
     # full path to unencrypted secrets file
     unenc_path="${filename%${secrets_suffix}}"
 
@@ -197,6 +205,13 @@ do
         echo "you might have to run 'git secret reveal -f' in secrets repo"
         exit 1
     fi
+
+    # remove leading path to secrets folder
+    path_into_vault="${unenc_path#$secrets_folder}"
+    # TODO: need to remove leading / - do this in one line ?
+    path_into_vault="${path_into_vault:1}"
+
+    secrets_json='{}'
 
     lines=$(<"${unenc_path}")
     for line in ${lines}
@@ -210,12 +225,58 @@ do
         secret_name="$( cut -d '=' -f 1 <<< "${line}")"
         secret_value="$(cut -d '=' -f 2 <<< "${line}")"
 
-        # TODO: does the line in file matter ?
-        echo "secret location : ${unenc_path}"
-        echo "secret name     : ${secret_name}"
-        echo "secret value    : ${secret_value}"
-        echo
+        echo -n "  add ${secret_name}: "
+        if output="$(jq --arg key   "${secret_name}"  \
+                        --arg value "${secret_value}" \
+                        '.[$key] = $value' <<< "${secrets_json}")"
+        then
+            echo 'OK'
+            secrets_json="${output}"
+        else
+            echo 'ERROR'
+            echo "  ${output}"
+        fi
     done
+
+    # TODO: this is taken 1:1 from .../code/vault/upload-secrets
+    # TODO: this expects the vault to be init'd and unsealed
+    # TODO: even when logged in, client token must be passed to curl
+    full_url="${vault_address}/${vault_prefix}/${path_into_vault}"
+
+    echo -n '  upload secrets to vault: '
+
+    # TODO: get root token from elsewhere
+    if output="$(curl --data   "${secrets_json}"              \
+                      --header "X-Vault-Token: 99f175af-1ad3-bbf2-2ee5-bbe5c20c59db" \
+                      --request POST                          \
+                      --show-error                            \
+                      --silent                                \
+                      "${full_url}" 2>&1)"
+    then
+        # if successful, curl returns 0 and output is empty
+        if [ -z "${output}" ]
+        then
+            echo 'OK'
+            echo "  ${full_url}"
+        else
+            echo 'ERROR'
+            # sample output:
+            # {"errors":["1 error occurred:\n\n* permission denied"]}
+            if errors="$(jq -r '.errors[]' <<< "${output}" 2>&1)"
+            then
+                echo "  ${errors}"
+            else
+                echo "  ${output}"
+            fi
+            exit 1
+        fi
+    else
+        echo 'ERROR'
+        echo "  ${output}"
+        exit 1
+    fi
+
+    echo
 done
 
 IFS="${OLD_IFS}"
