[#20]: refactor script from native functions to using BashLib

diff --git a/cicd/bin/build-basic-images b/cicd/bin/build-basic-images
--- a/cicd/bin/build-basic-images
+++ b/cicd/bin/build-basic-images
@@ -9,18 +9,15 @@
 # created : 2017-05-26
 
 
-# TODO: refactor this script to using an established tool (Kubernetes ?!?)
-# TODO: error handling around using jq and assuming paths being available
-# TODO: review / align script log output, especially during error handling
-# TODO: do stuff only if required - how to determine if stuff is required ?
-# TODO: verify required executables are available before attempting to use them;
-#  1. inspect PATH and add e.g. /usr/local/bin, then re-try
-#  2. if not found, display error message to tell user how to install, e.g.
-#
-# NOTE: on OS X, install required tools using
-#   brew install coreutils jq
+# NOTE: on OS X, install required packages using e.g.
+#   brew install bash coreutils jq yq
 # http://brew.sh/
 # http://apple.stackexchange.com/a/69332
+# https://stedolan.github.io/jq
+# http://mikefarah.github.io/yq
+
+# TODO: error handling around using jq and assuming paths being available
+# TODO: review / align script log output, especially during error handling
 
 
 echo
@@ -29,125 +26,40 @@ echo
 
 
 # -----------------------------------------------------------------------------
-# determine platform: http://stackoverflow.com/a/18434831
-
-# NOTE: running this on Linux as a non-privileged user
-# requires adding that user to the docker group
-# TODO: call (2009 MBP) can not run Docker natively,
-# alexa (2015 MBP) can; both run the same operation system
-
-case "${OSTYPE}" in
-    darwin*)
-        ;;
-    linux-*)
-        ;;
-    *)
-        echo "Unsupported operating system: ${OSTYPE}"
-        exit 1
-        ;;
-esac
-
-
-# -----------------------------------------------------------------------------
-# define functions
-
-# http://stackoverflow.com/a/6212408
-
-function usage
-{
-
-    # TODO: do not use global variables
-    # TODO: space between << and 'EOT' makes a
-    # difference for atom syntax highlighting
-    # TODO: align properly and remove leading space when printing ?
-
-    read -r -d '' msg_tmpl <<'EOT'
-Usage: %s <config file>
-
-mandatory arguments:
-  config file           absolute path to configuration file
-
-optional arguments:
-  -?, --help            print this help message
-EOT
-
-    # shellcheck disable=SC2059
-    printf "${msg_tmpl}\\n" "${script_name}"
-}
-
-
-# -----------------------------------------------------------------------------
-# process command line arguments
-
-# name of this script: http://stackoverflow.com/q/192319
-script_name="$(basename "$0")"
-
-if [ $# -ne 1 ]
-then
-    usage
-    exit 1
-fi
-
-# http://stackoverflow.com/a/14203146
-while [ $# -gt 0 ]
-do
-    key="$1"
-
-    case "${key}" in
-      # NOTE: must escape -?, seems to act as wildcard otherwise
-      -\?|--help) usage; exit 1 ;;
-
-      *)  if [ -z "${config_file}" ]
-          then
-              config_file="$1"
-          else
-              usage
-              exit 1
-          fi
-    esac
-
-    # move past argument or value
-    shift
-done
-
-# TODO: try to use ~/.<script_name>.yaml or so if no config file is passed ?
-
-# config file is a mandatory command line argument
-if [ -z "${config_file}" ]
-then
-    usage
-    exit 1
-fi
-
-# http://tldp.org/LDP/Bash-Beginners-Guide/html/sect_07_01.html
-if [ ! -e "${config_file}" ]
-then
-    echo "${config_file}: No such file or directory"
-    exit 1
-fi
-
-if [ ! -r "${config_file}" ]
-then
-    echo "${config_file}: File is not readable"
-    exit 1
-fi
-
-
-# -----------------------------------------------------------------------------
 # configure script parameters
 
-# absolute path to this script: http://stackoverflow.com/a/9107028
-path_to_this_script="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
+# NOTE: this script is meant to called standalone as well as
+# build subscript, so these variables are possibly already set:
+# http://wiki.bash-hackers.org/syntax/pe#use_a_default_value
+# TODO: the above is probably not true
 
 # path from this script to project root
-rel_path_to_project_root='../..'
+path_to_proj_root="${path_to_proj_root:-../..}"
 
-# absolute path to project root
-path_to_project_root="$(realpath \
-                        "${path_to_this_script}/${rel_path_to_project_root}")"
+# absolute path to this script: http://stackoverflow.com/a/9107028
+here="${here:-"$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"}"
 
-# path to folder with Docker files, relative to project root
-path_to_docker_folder='code/docker'
+# absolute, canonical path to project root
+# NOTE: realpath fails if path does not exist
+path_to_proj_root="$(realpath "${here}/${path_to_proj_root}")"
+
+# path to BashLib library file, relative to project root
+path_to_bashlib="${path_to_bashlib:-ext/BashLib/code/lib/bashlib.sh}"
+
+# absolute path to library
+path_to_library="${path_to_library:-"${path_to_proj_root}/${path_to_bashlib}"}"
+
+# TODO: shellcheck reports these to be unused
+# https://github.com/koalaman/shellcheck/wiki/SC2034
+
+# array with alphabetical list of tools called by this script
+# NOTE: too late to test for realpath, already used above
+# shellcheck disable=SC2034
+req_tools=('jq' 'yq')
+
+# array with paths to append to PATH
+# shellcheck disable=SC2034
+ext_paths=("${here}")
 
 # TODO: get these from config file ?
 
@@ -162,30 +74,69 @@ path_to_secrets_file='secrets'
 
 
 # -----------------------------------------------------------------------------
+# load BashLib
+
+# TODO: I just assumed BashLib would already be available here if this script
+# is called as subscript to build, as build sources it; this is not the case...
+# TODO: global flag in BashLib to test if library was already sourced ?
+
+# https://stackoverflow.com/a/85903
+if [ -z "$(type -t configure_platform)" ]
+then
+    # NOTE: this only tests if library can be sourced;
+    # functions are only defined in "$(...)" subshell,
+    # so a second source for use in here is required
+    # https://github.com/koalaman/shellcheck/wiki/SC1090
+    # shellcheck disable=SC1090
+    if ! output="$(source "${path_to_library}" 2>&1)"
+    then
+        echo "${output}"
+        exit 1
+    fi
+
+    # shellcheck disable=SC1090
+    source "${path_to_library}"
+fi
+
+
+# -----------------------------------------------------------------------------
+# run BashLib boilerplate functions
+
+if ! configure_platform              ; then exit 1; fi
+if ! extend_path req_tools ext_paths ; then exit 1; fi
+if ! proc_cmd_line_args "${@}"       ; then exit 1; fi
+
+
+# -----------------------------------------------------------------------------
 # load script configuration
 
 # NOTE: see config file for parameter documentation
+# TODO: refactor this out to BashLib function
 # TODO: error handling, e.g. check if json / yaml keys are available
-
-# http://mikefarah.github.io/yq
-config="$(yq r "${config_file}")"
-
-vault_addr="$(yq r - vault_addr <<< "${config}")"
+# TODO: get this to work with latest yq 2.x
 
 # NOTE: this essentially converts YAML to JSON
-cont_image_data="$(yq r -j - basic_images <<< "${config}")"
+# conf_file is defined by proc_cmd_line_args
+# https://github.com/koalaman/shellcheck/wiki/SC2154
+# shellcheck disable=SC2154
+conf="$(yq r -j "${conf_file}")"
+
+cont_image_data="$(jq -r '.basic_images' <<< "${conf}")"
+vault_addr="$(     jq -r '.vault_addr'   <<< "${conf}")"
 
 
 # -----------------------------------------------------------------------------
 # build basic Docker images
 
 
-if ! pushd "${path_to_project_root}" > /dev/null
+if ! pushd "${path_to_proj_root}" > /dev/null
 then
-    echo "Failed to pushd to project root ${path_to_project_root}"
+    echo "Failed to pushd to project root ${path_to_proj_root}"
     exit
 fi
 
+
+echo
 
 image_names="$(jq -r 'keys[]' <<< "${cont_image_data}" | sort)"
 
@@ -281,7 +232,7 @@ do
     fi
 
     if ! docker build --file "${path_to_dockerfile}" \
-                      --tag "${image_name}:${tag}" . 
+                      --tag "${image_name}:${tag}" .
     then
         exit 1
     fi
@@ -299,7 +250,7 @@ done
 
 if ! popd > /dev/null
 then
-    echo "Failed to popd from project root ${path_to_project_root}"
+    echo "Failed to popd from project root ${path_to_proj_root}"
     exit
 fi
 
