[#20]: refactor script from native functions to using BashLib

diff --git a/cicd/bin/upload b/cicd/bin/upload
--- a/cicd/bin/upload
+++ b/cicd/bin/upload
@@ -10,80 +10,100 @@
 
 
 # this script uploads a number of Docker container images to a registry
+# see also build and build-basic-images scripts
 
 
-# TODO: see also build script
-
-
-# -----------------------------------------------------------------------------
-# determine platform: http://stackoverflow.com/a/18434831
-
-# NOTE: running this on Linux as a non-privileged user
-# requires adding that user to the docker group
-
-case "${OSTYPE}" in
-    darwin*)
-        ;;
-    linux-*)
-        ;;
-    *)
-        echo "Unsupported operating system: ${OSTYPE}"
-        exit 1
-        ;;
-esac
+echo
+echo 'upload Docker container images'
+echo
 
 
 # -----------------------------------------------------------------------------
 # configure script parameters
 
-# absolute path to this script: http://stackoverflow.com/a/9107028
-path_to_this_script="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
-
 # path from this script to project root
-rel_path_to_project_root='../..'
+path_to_proj_root='../..'
 
-# absolute path to project root
-path_to_project_root="$(realpath \
-                        "${path_to_this_script}/${rel_path_to_project_root}")"
+# absolute path to this script: http://stackoverflow.com/a/9107028
+here="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
 
-# path to script configuration file, relative to project root
-path_to_conf_file='cicd/conf/ci.DesmoDyne.yaml'
+# absolute, canonical path to project root
+# NOTE: realpath fails if path does not exist
+path_to_proj_root="$(realpath "${here}/${path_to_proj_root}")"
+
+# path to BashLib library file, relative to project root
+path_to_bashlib='ext/BashLib/code/lib/bashlib.sh'
+
+# absolute path to library
+path_to_library="${path_to_proj_root}/${path_to_bashlib}"
+
+# TODO: shellcheck reports these to be unused
+# https://github.com/koalaman/shellcheck/wiki/SC2034
+
+# array with alphabetical list of tools called by this script
+# shellcheck disable=SC2034
+req_tools=('docker' 'jq' 'yq')
+
+# array with paths to append to PATH
+# shellcheck disable=SC2034
+ext_paths=("${here}")
+
+
+# -----------------------------------------------------------------------------
+# load BashLib
+
+# NOTE: this only tests if library can be sourced;
+# functions are only defined in "$(...)" subshell,
+# so a second source for use in here is required
+# https://github.com/koalaman/shellcheck/wiki/SC1090
+# shellcheck disable=SC1090
+if ! output="$(source "${path_to_library}" 2>&1)"
+then
+    echo "${output}"
+    exit 1
+fi
+
+# shellcheck disable=SC1090
+source "${path_to_library}"
+
+
+# -----------------------------------------------------------------------------
+# run BashLib boilerplate functions
+
+if ! configure_platform              ; then exit 1; fi
+if ! extend_path req_tools ext_paths ; then exit 1; fi
+if ! proc_cmd_line_args "${@}"       ; then exit 1; fi
 
 
 # -----------------------------------------------------------------------------
 # load script configuration
 
 # NOTE: see config file for parameter documentation
-# TODO: error handling, e.g. check if json / yaml keys are available
+# NOTE: this essentially converts YAML to JSON
+# conf_file is defined by proc_cmd_line_args
+# https://github.com/koalaman/shellcheck/wiki/SC2154
+# shellcheck disable=SC2154
+conf="$(yq r -j "${conf_file}")"
 
-# http://mikefarah.github.io/yq
-config="$(yq r "${path_to_conf_file}")"
-
-cont_namespace="$( yq r - cont_namespace <<< "${config}")"
-
-# NOTE: the first line essentially converts YAML to JSON,
-# the second line extracts basic and complex image configuration
-cont_image_data="$(yq r -j - <<< "${config}" \
-                     | jq '.basic_images + .complex_images')"
+cont_image_data="$(jq -r '.basic_images + .complex_images' <<< "${conf}")"
+cont_namespace="$( jq -r '.cont_namespace'                 <<< "${conf}")"
 
 
 # -----------------------------------------------------------------------------
 # upload project artifacts
 
 
-if ! pushd "${path_to_project_root}" > /dev/null
+if ! pushd "${path_to_proj_root}" > /dev/null
 then
-    echo "Failed to pushd to project root ${path_to_project_root}"
+    echo "Failed to pushd to project root ${path_to_proj_root}"
     exit
 fi
 
 
-# https://unix.stackexchange.com/a/76407
-if ! image_names="$(jq -r ". | keys[]" <<< "${cont_image_data}")"
+if ! image_names="$(jq -r 'keys[]' <<< "${cont_image_data}" | sort)"
 then
     exit 1
 fi
-
 
 for image_name in ${image_names}
 do
@@ -96,7 +116,7 @@ do
     echo
 
     if ! public_name="$(jq -r ".\"${image_name}\".public_name" \
-             <<< "${cont_image_data}")"
+          <<< "${cont_image_data}")"
     then
         exit 1
     fi
@@ -131,14 +151,13 @@ do
         exit 1
     fi
 
-    # NOTE: docker push displays its own output
+    # NOTE: docker rmi displays its own output
     echo
     echo 'Remove repository info tag from Docker container:'
     if ! docker rmi "${repo_tag}"
     then
         exit 1
     fi
-
 
     echo
     echo "container image ${image_name} upload complete"
@@ -148,6 +167,10 @@ done
 
 if ! popd > /dev/null
 then
-    echo "Failed to popd from project root ${path_to_project_root}"
+    echo "Failed to popd from project root ${path_to_proj_root}"
     exit
 fi
+
+
+echo 'Docker container images upload complete'
+echo
