[#7]: deal with service or user names containing a path component

diff --git a/code/vault/create-policies-files b/code/vault/create-policies-files
--- a/code/vault/create-policies-files
+++ b/code/vault/create-policies-files
@@ -88,8 +88,8 @@ user_tmpl_data_tmpl_name='user_policy_tmpl.json.j2'
 # }
 # EOT
 
-# full path to folder with policies configuration files
-path_to_policies_folder="${path_to_sec_loc}/${policies_folder}"
+# full path to root folder for policies configuration files
+path_to_policies_root="${path_to_sec_loc}/${policies_folder}"
 
 
 # -----------------------------------------------------------------------------
@@ -109,19 +109,6 @@ then
 fi
 
 
-if [ ! -d "${path_to_policies_folder}" ]
-then
-    echo -n 'create policies configuration folder: '
-    if output="$(mkdir -p "${path_to_policies_folder}" 2>&1)"
-    then
-        echo 'OK'
-    else
-        echo 'ERROR'
-        echo "${output}"
-        exit 1
-    fi
-fi
-
 # TODO: continue or exit ?
 
 if [ -z "${serv_secrets}" ]
@@ -131,11 +118,13 @@ else
     serv_names="$(jq -r '.sec_confs[].path' <<< "${serv_secrets}" | xargs)"
 fi
 
+# NOTE: serv_name possibly contains a path component
+# TODO: if serv_name has a path component, the name does not match the function
 for serv_name in ${serv_names}
 do
     echo "service ${serv_name}:"
 
-    path_to_conf_file="${path_to_policies_folder}/${serv_name}.hcl"
+    path_to_conf_file="${path_to_policies_root}/${serv_name}.hcl"
 
     echo -n '  render service policy template data template: '
     # j2 --format env requires export
@@ -171,6 +160,21 @@ do
         exit 1
     fi
 
+    path_to_policies_folder="$(dirname "${path_to_conf_file}")"
+
+    if [ ! -d "${path_to_policies_folder}" ]
+    then
+        echo -n '  create service policy configuration folder: '
+        if output="$(mkdir -p "${path_to_policies_folder}" 2>&1)"
+        then
+            echo 'OK'
+        else
+            echo 'ERROR'
+            echo "${output}"
+            exit 1
+        fi
+    fi
+
     echo -n '  create service policy configuration file: '
 
     if output="$(echo "${policy_conf}" 2>&1 > "${path_to_conf_file}")"
@@ -197,7 +201,7 @@ for user_name in ${user_names}
 do
     echo "user ${user_name}:"
 
-    path_to_conf_file="${path_to_policies_folder}/${user_name}.hcl"
+    path_to_conf_file="${path_to_policies_root}/${user_name}.hcl"
 
     echo -n '  render user policy template data template: '
     export user_name="${user_name}"
@@ -230,6 +234,21 @@ do
         echo 'ERROR'
         echo "  ${output}"
         exit 1
+    fi
+
+    path_to_policies_folder="$(dirname "${path_to_conf_file}")"
+
+    if [ ! -d "${path_to_policies_folder}" ]
+    then
+        echo -n '  create user policy configuration folder: '
+        if output="$(mkdir -p "${path_to_policies_folder}" 2>&1)"
+        then
+            echo 'OK'
+        else
+            echo 'ERROR'
+            echo "${output}"
+            exit 1
+        fi
     fi
 
     echo -n '  create user policy configuration file: '
diff --git a/code/vault/create-secrets-files b/code/vault/create-secrets-files
--- a/code/vault/create-secrets-files
+++ b/code/vault/create-secrets-files
@@ -76,7 +76,7 @@ path_to_project_root="$(realpath \
 
 # absolute path to folder with secrets configuration files
 # TODO: with the current config, this results in /opt/vault/secrets/secrets/
-path_to_secrets_folder="${path_to_sec_loc}/${secrets_folder}"
+path_to_secrets_root="${path_to_sec_loc}/${secrets_folder}"
 
 # name of service secret template file
 srv_sec_tmpl='service_secret.yaml.j2'
@@ -120,19 +120,6 @@ then
 fi
 
 
-if [ ! -d "${path_to_secrets_folder}" ]
-then
-    echo -n 'create secrets configuration folder: '
-    if output="$(mkdir -p "${path_to_secrets_folder}" 2>&1)"
-    then
-        echo 'OK'
-    else
-        echo 'ERROR'
-        echo "${output}"
-        exit 1
-    fi
-fi
-
 # TODO: continue or exit ?
 # TODO: remove code duplication
 
@@ -168,7 +155,7 @@ do
     echo -n '  add known secrets to template data: '
 
     # TODO: do not hard-code file suffix
-    path_to_conf_file="${path_to_secrets_folder}/${serv_name}.yaml"
+    path_to_conf_file="${path_to_secrets_root}/${serv_name}.yaml"
 
     num_of_sec_confs="$(jq -r '.sec_confs | length' <<< "${serv_secrets}")"
 
@@ -213,6 +200,7 @@ do
     done
 
     # add service to template data
+    # TODO: align this between here and users below
     serv_secrets="$(jq --arg  service "${serv_name}" \
                                '. + { service: $service }' \
                                 <<< "${serv_secrets}")"
@@ -220,19 +208,47 @@ do
     echo 'OK'
 
     # TODO: do not hard-code file suffix
-    path_to_temp_file="${path_to_secrets_folder}/${serv_name}.yaml.temp"
+    path_to_temp_file="${path_to_secrets_root}/${serv_name}.yaml.temp"
 
-    echo -n '  render template into configuration file: '
+    echo -n '  render service secrets template: '
     if output="$(j2 --format json "${path_to_tmpl_folder}/${srv_sec_tmpl}" \
                               <<< "${tmpl_data}" 2>&1)"
     then
         echo 'OK'
-        echo "${output}" > "${path_to_temp_file}"
+        secrets_conf="${output}"
     else
         echo 'ERROR'
         echo "  ${output}"
         exit 1
     fi
+
+    path_to_secrets_folder="$(dirname "${path_to_conf_file}")"
+
+    if [ ! -d "${path_to_secrets_folder}" ]
+    then
+        echo -n '  create service secrets configuration folder: '
+        if output="$(mkdir -p "${path_to_secrets_folder}" 2>&1)"
+        then
+            echo 'OK'
+        else
+            echo 'ERROR'
+            echo "${output}"
+            exit 1
+        fi
+    fi
+
+    echo -n '  create service secrets configuration file: '
+
+    if output="$(echo "${secrets_conf}" 2>&1 > "${path_to_temp_file}")"
+    then
+        echo 'OK'
+    else
+        echo 'ERROR'
+        echo "  ${output}"
+        exit 1
+    fi
+
+    # TODO: this is only safe as long as temp and final file are in the same folder
 
     # move temp file to conf file
     if ! output="$(mv "${path_to_temp_file}" "${path_to_conf_file}" 2>&1)"
@@ -275,7 +291,7 @@ do
     echo '  add known secrets to template data:'
 
     # TODO: do not hard-code file suffix
-    path_to_conf_file="${path_to_secrets_folder}/${user_name}.yaml"
+    path_to_conf_file="${path_to_secrets_root}/${user_name}.yaml"
 
     num_of_sec_confs="$(jq -r '.sec_confs | length' <<< "${user_secrets}")"
 
@@ -415,6 +431,7 @@ do
     # iterates over sec_confs; if its value is unchanged, no secret key / value
     # pairs were addedsecrets were added to secrets_json_map and thus no
     # template data was assembled, there is no point in rendering a conf file
+    # TODO: why is this done for users, but not for secrets ?
     if [ "${tmpl_data}" = "${user_secrets}" ]
     then
         echo '  no usable secrets; file not created'
@@ -426,25 +443,47 @@ do
                     '. + { user_name: $user_name }' \
                   <<< "${tmpl_data}")"
 
-    echo '  create user secrets configuration file:'
-
     # TODO: do not hard-code file suffix
-    path_to_temp_file="${path_to_secrets_folder}/${user_name}.yaml.temp"
-    echo "${path_to_conf_file}"
+    path_to_temp_file="${path_to_secrets_root}/${user_name}.yaml.temp"
 
-    echo -n '  render template into configuration file: '
-
+    echo -n '  render user secrets template: '
     if output="$(j2 --format json "${path_to_tmpl_folder}/${user_sec_tmpl}" \
                   <<< "${tmpl_data}" 2>&1)"
     then
         echo 'OK'
-        echo "${output}" > "${path_to_temp_file}"
+        secrets_conf="${output}"
     else
         echo 'ERROR'
         echo "  ${output}"
         exit 1
     fi
     echo
+
+    path_to_secrets_folder="$(dirname "${path_to_conf_file}")"
+
+    if [ ! -d "${path_to_secrets_folder}" ]
+    then
+        echo -n '  create user secrets configuration folder: '
+        if output="$(mkdir -p "${path_to_secrets_folder}" 2>&1)"
+        then
+            echo 'OK'
+        else
+            echo 'ERROR'
+            echo "${output}"
+            exit 1
+        fi
+    fi
+
+    echo -n '  create user secrets configuration file: '
+
+    if output="$(echo "${secrets_conf}" 2>&1 > "${path_to_temp_file}")"
+    then
+        echo 'OK'
+    else
+        echo 'ERROR'
+        echo "  ${output}"
+        exit 1
+    fi
 
     # move temp file to conf file
     if ! output="$(mv "${path_to_temp_file}" "${path_to_conf_file}" 2>&1)"
