[#7]: add missing sec confs; debug script and template

diff --git a/code/vault/create-secrets-files b/code/vault/create-secrets-files
--- a/code/vault/create-secrets-files
+++ b/code/vault/create-secrets-files
@@ -50,8 +50,9 @@ secrets_json="$(       jq -r '.secrets'             <<< "${config}")"
 
 # TODO: review jq exprs to make these scalable beyond one path
 
-# json data structure with secrets for each service
-serv_secrets="$(jq '.[] | select(.context=="service")' <<< "${secrets_json}")"
+# json data structure with secrets for all services
+jq_expr='.[] | select(.context=="service")'
+all_serv_secrets="$(jq "${jq_expr}" <<< "${secrets_json}")"
 
 # json data structure with secrets for each user
 user_secrets="$(jq '.[] | select(.context=="user")'    <<< "${secrets_json}")"
@@ -95,9 +96,14 @@ mgmt_key_filename_tmpl="id_rsa_${organization}_${mgmt_user_name}_%s_rs"
 # sample name: id_rsa_desmodyne_ssc_rs
 pers_key_filename_tmpl="id_rsa_${organization}_%s_rs"
 
+# jq expression template to get secrets for one service
+# jq_expr_one_serv='.sec_confs[] | select(.path=="%s") | del(.path)'
+jq_expr_one_serv='.sec_confs[] | select(.path=="%s")'
+
 # jq expression template to get service secrets from existing secrets file
 # NOTE: secret/user/ must be in sync with .../data/tmpl/user_secret.yaml.j2
-jq_expr_tmpl_serv='.[] | from_entries | .secrets | from_entries | .%s'
+jq_expr_tmpl_serv='.[] | from_entries | select(.path=="secret/service/%s") | '
+jq_expr_tmpl_serv+='.secrets | from_entries | .%s'
 
 # jq expression template to get user passwords from existing secrets file
 # NOTE: secret/user/ must be in sync with .../data/tmpl/user_secret.yaml.j2
@@ -123,16 +129,29 @@ fi
 # TODO: continue or exit ?
 # TODO: remove code duplication
 
-if [ -z "${serv_secrets}" ]
+if [ -z "${all_serv_secrets}" ]
 then
     echo 'no services configured; skip creating service secrets files'
 else
-    serv_names="$(jq -r '.sec_confs[].path' <<< "${serv_secrets}" | xargs)"
+    serv_names="$(jq -r '.sec_confs[].path' <<< "${all_serv_secrets}" | xargs)"
 fi
 
 for serv_name in ${serv_names}
 do
     echo "service ${serv_name}:"
+
+    echo -n '  extract secrets for service: '
+
+    jq_expr="$(printf "${jq_expr_one_serv}" "${serv_name}")"
+    if output="$(jq "${jq_expr}" <<< "${all_serv_secrets}" 2>&1)"
+    then
+        echo 'OK'
+        serv_secrets="${output}"
+    else
+        echo 'ERROR'
+        echo "  ${output}"
+        exit 1
+    fi
 
     # secrets json data structure as obtained from conf file:
     #   "secrets":
@@ -157,50 +176,44 @@ do
     # TODO: do not hard-code file suffix
     path_to_conf_file="${path_to_secrets_root}/${serv_name}.yaml"
 
-    num_of_sec_confs="$(jq -r '.sec_confs | length' <<< "${serv_secrets}")"
-
     tmpl_data="${serv_secrets}"
 
-    for index in $(seq 0 "$((num_of_sec_confs - 1))")
+    secret_keys="$(jq -r ".secrets[]" <<< "${serv_secrets}" | xargs)"
+
+    secrets_json_map='{}'
+
+    for secret_key in ${secret_keys}
     do
-        secret_keys="$(jq -r ".sec_confs[${index}].secrets[]" \
-                        <<< "${serv_secrets}" | xargs)"
+        secret_value="${placeholder}"
 
-        secrets_json_map='{}'
+        # attempt to get secret from existing file
+        if [ -f "${path_to_conf_file}" ]
+        then
+            # shellcheck disable=SC2059
+            jq_expr="$(printf "${jq_expr_tmpl_serv}" \
+                              "${serv_name}" "${secret_key}")"
 
-        for secret_key in ${secret_keys}
-        do
-            secret_value="${placeholder}"
-
-            # attempt to get secret from existing file
-            if [ -f "${path_to_conf_file}" ]
+            if output="$(yq r -j "${path_to_conf_file}" \
+                         | jq -r "${jq_expr}"  2>&1)"
             then
-                # shellcheck disable=SC2059
-                jq_expr="$(printf "${jq_expr_tmpl_serv}" "${secret_key}")"
-
-                if output="$(yq r -j "${path_to_conf_file}" \
-                             | jq -r "${jq_expr}"  2>&1)"
+                if [ "${output}" != 'null' ]
                 then
-                    if [ "${output}" != 'null' ]
-                    then
-                        secret_value="${output}"
-                    fi
+                    secret_value="${output}"
                 fi
             fi
+        fi
 
-            # extend json object:      https://stackoverflow.com/q/31694182
-            # parentheses around $key: https://stackoverflow.com/a/35842157
-            secrets_json_map="$(jq --arg key   "${secret_key}"    \
-                                   --arg value "${secret_value}"  \
-                                   '. += { ($key): $value }' \
-                                 <<< "${secrets_json_map}")"
-        done
-
-        # replace secrets array in template data with secrets object
-        tmpl_data="$(jq --argjson secrets "${secrets_json_map}"     \
-                        ".sec_confs[${index}].secrets = \$secrets"  \
-                      <<< "${tmpl_data}")"
+        # extend json object:      https://stackoverflow.com/q/31694182
+        # parentheses around $key: https://stackoverflow.com/a/35842157
+        secrets_json_map="$(jq --arg key   "${secret_key}"    \
+                               --arg value "${secret_value}"  \
+                               '. += { ($key): $value }' \
+                             <<< "${secrets_json_map}")"
     done
+
+    # replace secrets array in template data with secrets object
+    tmpl_data="$(jq --argjson secrets "${secrets_json_map}" \
+                    ".secrets = \$secrets" <<< "${tmpl_data}")"
 
     # add service to template data
     # TODO: align this between here and users below
