[#7]: align scripts to support relative paths to secure location

diff --git a/code/vault/init-vault b/code/vault/init-vault
--- a/code/vault/init-vault
+++ b/code/vault/init-vault
@@ -53,6 +53,16 @@ if ! validate_config_settings;      then exit 1; fi
 # -----------------------------------------------------------------------------
 # configure script parameters
 
+# absolute path to this script: http://stackoverflow.com/a/9107028
+path_to_this_script="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
+
+# path from this script to project root
+rel_path_to_project_root='../..'
+
+# absolute path to project root
+path_to_project_root="$(realpath \
+                        "${path_to_this_script}/${rel_path_to_project_root}")"
+
 # TODO: use template file instead of code ?
 # template for http call json data
 read -r -d '' json_data_tmpl <<'EOT'
@@ -95,6 +105,14 @@ fi
 
 # -----------------------------------------------------------------------------
 # init vault
+
+
+if ! pushd "${path_to_project_root}" > /dev/null
+then
+    echo "failed to pushd to project root ${path_to_project_root}"
+    exit
+fi
+
 
 if [ ! -d "${path_to_sec_loc}" ]
 then
@@ -154,6 +172,13 @@ else
     echo 'ERROR'
     echo "${output}"
     exit 1
+fi
+
+
+if ! popd > /dev/null
+then
+    echo "failed to popd from project root ${path_to_project_root}"
+    exit
 fi
 
 
diff --git a/code/vault/set-up-auth-userpass b/code/vault/set-up-auth-userpass
--- a/code/vault/set-up-auth-userpass
+++ b/code/vault/set-up-auth-userpass
@@ -55,6 +55,16 @@ if ! validate_config_settings;      then exit 1; fi
 # -----------------------------------------------------------------------------
 # configure script parameters
 
+# absolute path to this script: http://stackoverflow.com/a/9107028
+path_to_this_script="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
+
+# path from this script to project root
+rel_path_to_project_root='../..'
+
+# absolute path to project root
+path_to_project_root="$(realpath \
+                        "${path_to_this_script}/${rel_path_to_project_root}")"
+
 # full path to file with key and token info
 path_to_key_file="${path_to_sec_loc}/${key_file_name}"
 
@@ -81,6 +91,13 @@ fi
 
 # -----------------------------------------------------------------------------
 # set up userpass authentication
+
+
+if ! pushd "${path_to_project_root}" > /dev/null
+then
+    echo "failed to pushd to project root ${path_to_project_root}"
+    exit
+fi
 
 
 if [ "${users_json}" = 'null' ]
@@ -240,6 +257,13 @@ do
         exit 1
     fi
 done
+
+
+if ! popd > /dev/null
+then
+    echo "failed to popd from project root ${path_to_project_root}"
+    exit
+fi
 
 
 echo
diff --git a/code/vault/upload-secrets b/code/vault/upload-secrets
--- a/code/vault/upload-secrets
+++ b/code/vault/upload-secrets
@@ -64,6 +64,16 @@ if ! validate_config_settings;      then exit 1; fi
 # -----------------------------------------------------------------------------
 # configure script parameters
 
+# absolute path to this script: http://stackoverflow.com/a/9107028
+path_to_this_script="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
+
+# path from this script to project root
+rel_path_to_project_root='../..'
+
+# absolute path to project root
+path_to_project_root="$(realpath \
+                        "${path_to_this_script}/${rel_path_to_project_root}")"
+
 # full path to file with key and token info
 path_to_key_file="${path_to_sec_loc}/${key_file_name}"
 
@@ -94,6 +104,14 @@ fi
 # https://www.vaultproject.io/api/secret/kv/index.html
 
 # TODO: only do this if any services or users are configured
+
+
+if ! pushd "${path_to_project_root}" > /dev/null
+then
+    echo "failed to pushd to project root ${path_to_project_root}"
+    exit
+fi
+
 
 root_token="$(jq -r '.root_token' "${path_to_key_file}")"
 
@@ -328,6 +346,13 @@ do
         fi
     done
 done
+
+
+if ! popd > /dev/null
+then
+    echo "failed to popd from project root ${path_to_project_root}"
+    exit
+fi
 
 
 echo
